#!/public3/home/scg6928/mysoft/env/pyenv/dft/bin/python
# pei_vasp_plot_E_in_1_2_bulk.py
#  >>> Post-process a finished y_E_in_1_2_bulk tree: energy vs the uniaxial / biaxial
#      in-plane stretch generated by pei_vasp_run_E_in_1_2_bulk.
import argparse
import os
from ase.io import write, read
from myvasp import vasp_func as vf
from mymetal.post.general import my_read_y_dir_contcar
from mymetal.post.E_in_1_2_bulk import post_E_in_1_2_bulk

# Takes no options. It is run from INSIDE y_E_in_1_2_bulk (that is how pei_vasp_plot_all
# calls it) and chdir's one level up to find y_full_relax/CONTCAR as the reference cell.
# Parse first, so --help answers without moving the caller's cwd or running univ_post.
EPILOG = """\
most common:
  pei_vasp_plot_all -E_in_1_2_bulk               # usual entry point: every tree found
  cd y_E_in_1_2_bulk && pei_vasp_plot_E_in_1_2_bulk.py
                                                 # plot a single tree by hand

writes into y_E_in_1_2_bulk/:
  p_post_E_in_1_2_bulk.pdf / p_post_E_in_1_2_bulk2.pdf   energy vs strain
  p_post_E_in_1_2_bulk.txt                               the fitted table
  movie.xyz                                              all CONTCARs, for viewing

notes:
  takes no options. run it from INSIDE y_E_in_1_2_bulk: it chdir's one level up and uses
  y_full_relax/CONTCAR as the reference cell, so that dir must still be there.
  it re-runs pei_vasp_univ_post itself; run it only once the jobs have finished.
"""

parser = argparse.ArgumentParser(
    description="Plot energy vs uniaxial/biaxial in-plane stretch from a finished "
                "y_E_in_1_2_bulk tree.",
    epilog=EPILOG, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.parse_args()

# Pre-pare data

################### This part maybe need to be changed

# e. g. "****/20231215_strain_energy_fcc_hcp/more_strain_uniaxial_biaxial_bulk_fcc_hcp/fcc"
# Already cd the workflow root
os.chdir("..")
myroot = os.getcwd()
workflow_root = os.path.join(myroot, "y_E_in_1_2_bulk")
post_data_path = os.path.join(workflow_root, "y_post_data.txt")
y_dir_path = os.path.join(workflow_root, "y_dir")
refcontcar_path = os.path.join(myroot, "y_full_relax/CONTCAR")
latoms_path = os.path.join(workflow_root, "movie.xyz")
save_fig_path = os.path.join(workflow_root, "p_post_E_in_1_2_bulk.pdf")
save_fig_path2 = os.path.join(workflow_root, "p_post_E_in_1_2_bulk2.pdf")
save_txt_path = os.path.join(workflow_root, "p_post_E_in_1_2_bulk.txt")
################### To here

os.chdir(workflow_root)
os.system("pei_vasp_univ_post")

jobn, Etot, Eent, pres = vf.vasp_read_post_data(post_data_path)
latoms = my_read_y_dir_contcar(dir = y_dir_path, post_data_file = post_data_path)
atoms_ref = read(refcontcar_path)
# For viewing
write(latoms_path, latoms, format='extxyz')

post_E_in_1_2_bulk(jobn = jobn, Etot = Etot,
                   atoms_ref = atoms_ref,
                   latoms = latoms,
                   save_fig_path = save_fig_path, 
                   save_fig_path2 = save_fig_path2,
                   save_txt_path = save_txt_path
                   )