#!/bin/bash
# B. Yin, 2022-03-09
# Revised by J. Pei, 2024-12-05
# echo -e  "3\n0.0  0.0  0.0  0.0  0.0  0.0" > Y_CONSTR_LATT
# example: pei_vasp_run_E_in_2_bulk_large_strain  10 20 30 1 0.1 0.2

main(){
    srcdir0=y_full_relax

    if [ -d "$srcdir0" ]
    then
        sub_run_E_in_2_slab $@
    else
        echo "==> no $srcdir0 found! Abort!"
        exit
    fi
}





sub_run_E_in_2_slab(){
    srcdir=`pwd`/y_full_relax_temp
    rm -rf $srcdir

    cp -r $srcdir0  $srcdir 
    cd $srcdir

    echo "==> equi-biaxial stretch for bulk"
    echo "    Please confirm that a0 is the variable you are concerned about"
    echo "example: pei_vasp_run_E_in_2_bulk_large_strain  2.7 2.8 2.9 3.0"

    myfile=./CONTCAR 
    if [ -f "$myfile" ]; then
        echo "$myfile exists."
    else 
        echo "$myfile does not exist. cp POSCAR CONTCAR "
        cp POSCAR CONTCAR
    fi

    yin_vasp_univ_find_and_change  -isif  3
    echo -e  "3\n0.0  0.0  0.0  0.0  0.0  0.0" > Y_CONSTR_LATT
 
    cd ..


    
    #--------------------   

    a0=`sed -n '2,2p' $srcdir/CONTCAR | awk '{printf "%.16f", $1}'`
    
    c1=`sed -n '5,5p' $srcdir/CONTCAR | awk '{printf "%.16f", $1}'`
    c2=`sed -n '5,5p' $srcdir/CONTCAR | awk '{printf "%.16f", $2}'`
    c3=`sed -n '5,5p' $srcdir/CONTCAR | awk '{printf "%.16f", $3}'`

    echo $a0
    echo $c1 $c2 $c3
    
    
    #=====================
    
    dirCij=y_E_in_2_bulk_large_strain
    
    rm -rI  $dirCij
    mkdir   $dirCij
    cd      $dirCij
    
    mkdir y_dir
    cd    y_dir
    
    #=====================

    for num in "$@"; do

        el=$(echo "scale=16; $num/$a0" | bc)
        
        num2=`printf "%.16f" "$num"`
        dirn=`printf "%.4f" "$num"`
        echo ================ $dirn
        mkdir $dirn
        cd $dirn

        cp $srcdir/{INCAR,KPOINTS,CONTCAR,POTCAR,sub.*,Y_*,CHGCAR} ./
        mv CONTCAR POSCAR

        a0new=`echo "scale=16; $num2" | bc`
        yin_vasp_univ_find_and_change  -a0  $a0new  
        # $c3/$el - original c3
        # /$el/$el - for volume conserving
        c3new=`echo "scale=16; $c3/$el/$el/$el" | bc `
        yin_vasp_univ_find_and_change  -a3  " $c1  $c2  $c3new "

        echo 'submit dir:' `pwd`
        sbatch sub.*
        cd ..
    done

    rm -rf $srcdir
}



main "$@"; exit




