#!/bin/bash
# B. Yin

workdir=./y_dir      # work dir, comment it to be safe

cd $workdir


#=====================
# loop
#=====================

for i1 in `ls .`
do

cd $i1
echo '====================' $i1


file=CONTCAR
minimumsize=0
actualsize=$(wc -c <"$file")
if [ $actualsize -gt $minimumsize ]; then
    echo size of $file is greater than $minimumsize bytes, copying...
    cp CONTCAR POSCAR
else
    echo size of $file is $minimumsize bytes
fi


yin_vasp_univ_update_MAGMOM


echo 'dir for submit:' `pwd`
sbatch sub.*


cd ..

done


