#!/bin/bash
# J. Pei, 2024-11-10


main(){
    srcdir0=y_full_relax
    # scf y_full_relax
    echo "==> dos band calculation"
    echo "Note: You must follow those step"
    echo "In y_full_relax: structure optimization; ISIF=3;"
    echo "                 vaspkit -task 303; cp PRIM.VASP POSCAR; sbatch sub.vasp; ISIF=2"
    echo "                 scf; NSW=0; ISIF=2; IBRION=-1"
    if [ -d "$srcdir0" ]
    then
        sub_run_dos_bs $1
    else
        echo "==> no $srcdir0 found! Abort!"
        exit
    fi
}

sub_run_dos_bs(){
    srcdir=`pwd`/y_full_relax_temp
    rm -rf $srcdir

    cp -r $srcdir0  $srcdir 
    cd $srcdir

    myfile=./POSCAR
    if [ -f "$myfile" ]; then
        echo "$myfile exists."
    else
        echo "$myfile does not exist. cp CONTCAR POSCAR"
        cp CONTCAR POSCAR
    fi

   #--------------------
    pei_vasp_univ_find_and_change  -isym  1
    pei_vasp_univ_find_and_change  -isif  2
    pei_vasp_univ_find_and_change  -nsw   0
    pei_vasp_univ_find_and_change  -ibrion -1
    pei_vasp_univ_find_and_change  -nedos 3000
    pei_vasp_univ_find_and_change  -lorbit 11

    kpath=KPATH.in
    if [ -f "$kpath" ]; then
        echo "$kpath exists."
        sed -i '2s/.*/     60/' KPATH.in
    else
        echo "$kpath does not exist. You need to run vaspkit -task 303"
        exit
    fi
    echo -e "0\n0.0  0.0  0.0  0.0  0.0  0.0" > Y_CONSTR_LATT

    cd ..
    #=====================

    dirsurf=y_dos_bs

    rm -rI $dirsurf
    mkdir  $dirsurf
    cd     $dirsurf

    mkdir  y_dir
    cd     y_dir

    ####################################### work here
    dirn=dos
    echo ================ $dirn

    mkdir $dirn
    cd    $dirn

    cp $srcdir/{INCAR,KPOINTS,POSCAR,POTCAR,sub.*,Y_*,CHGCAR} ./
    pei_vasp_univ_find_and_change -ismear -5

    echo 'submit dir:' `pwd`
    sbatch sub.*
    cd ..

    dirn=bs
    echo ================ $dirn

    mkdir $dirn
    cd    $dirn

    cp $srcdir/{INCAR,KPATH.in,POSCAR,POTCAR,sub.*,Y_*,CHGCAR} ./
    mv $kpath KPOINTS
    pei_vasp_univ_find_and_change -icharg 11
    pei_vasp_univ_find_and_change -lmaxmix 4

    echo 'submit dir:' `pwd`
    sbatch sub.*
    cd ..

    rm -rf $srcdir
}

main "$@"; exit
