#!/bin/bash
# taken from https://github.com/BinglunYin/vasp_utils
# revised by J. Pei, 2025-05-29
# 
if [ -z "$1" ]; then      # empty is true 
    echo "==>  Please indicate what to plot. Abort!"
    exit 
fi


d0=`pwd`

sub_plot_all(){
    workdir="$1"
    mycmd=$2
    echo "==> workdir: "  "$workdir"
    echo "==> mycmd: "     $mycmd

    mylist=`find ./ -type d -name "$workdir"`
    echo mylist $mylist
    for dirn in $mylist ; do
        cd $dirn
        echo -e "\n==>" `pwd`
    
        # move to $cmd
        # yin_vasp_univ_post 
        python3  $mycmd
    
        cd $d0
    done


    echo -e "\n==> ${FUNCNAME[0]} summary: "
    
    
    for dirn in $mylist ; do
        cd $dirn
        temproot=`pwd`
        echo -e "\n==> $temproot"
        workdir2=y_dir
        # dir counts
        dc=`find ./ -type d -name $workdir2  -print | wc -l`
        echo -e "\n==> Number of $workdir2: $dc "
        mylist2=$(find ./ -type d -name "$workdir2" -exec dirname {} \;)
        for dirn2 in $mylist2 ; do
            echo -e "\n==> $dirn2"
            cat -n $dirn2/y_post_time.txt
            grep -n "Your highest band" $dirn2/y_post_warning.txt
        done
        cd $d0
        echo " "
    done
    echo " "

}




case "$1" in


    -convergence)
        workdir=y_convergence
        mycmd=$PJ_MYMETAL/vasp_utils/vasp_workflow_bulk/pei_vasp_plot_convergence.py
        sub_plot_all  $workdir  $mycmd 
        ;;


    -neb)
        workdir=y_neb
        mycmd=$PJ_MYMETAL/vasp_utils/vasp_workflow_bulk/pei_vasp_plot_neb.py
        sub_plot_all  $workdir  $mycmd 
        ;;


    -stretch)
        workdir=y_stretch
        mycmd=$PJ_MYMETAL/vasp_utils/vasp_workflow_bulk/pei_vasp_plot_stretch.py
        sub_plot_all  $workdir  $mycmd 
        ;;

    -E_in_1_2_bulk_large_strain)
        workdir=y_E_in_1_2_bulk_large_strain
        mycmd=$PJ_MYMETAL/vasp_utils/vasp_workflow_bulk/pei_vasp_plot_E_in_1_2_bulk.py
        sub_plot_all  $workdir  $mycmd 
        ;;

    *) 
        echo "==>  Option $1 not recognized. Abort!" 
        exit
        ;;   
esac




