
import argparse
import os
import shutil
import string
import subprocess
import sys
import textwrap
from pathlib import Path
import numpy as np

def pr(text=""):
    print(text)

def er(text=""):
    print(text)

def warn(msg):
    print(f"⚠️  {msg}")

def fail(msg):
    print(f"❌ ERROR: {msg}")
    raise SystemExit(1)

# generate_script

def generate_script_header(partition: str, nodes: int, ncores: int, module_profile_type: str, MODULE_BLOCKS: dict[str, str]):
    header = (
        "#!/bin/bash\n"
        f"#SBATCH -p {partition}\n"
        f"#SBATCH -N {nodes}\n"
        f"#SBATCH -n {ncores}\n"
    )
    module_block = MODULE_BLOCKS.get(module_profile_type)
    if module_block is None:
        fail(f"Unknown module profile type: {module_profile_type}")
    header += module_block
    return header

def generate_launcher_command(launcher: str, cmd: str, if_use_my_launcher: bool = False):
    line_launcher = ""

    # 裸变量写法两处通用：$SLURM_NTASKS 是纯数字，无需内层引号防 word splitting。
    if launcher == "srun":
        line_launcher_1 = 'srun -n $SLURM_NTASKS'
    elif launcher == "mpirun":
        line_launcher_1 = 'mpirun -np $SLURM_NTASKS'
    elif launcher == "none":
        line_launcher_1 = ""
    else:
        fail(f"Unknown launcher type: {launcher}")

    line_launcher_2 = cmd

    # 对于一些封装好的脚本，可能需要通过环境变量传递launcher类型，而不是直接在脚本里写死，例如 srun -n "$SLURM_NTASKS" cmd
    # 而对于 n2p2, vasp 一些直接调用可执行文件的，直接在脚本里写死 srun -n "$SLURM_NTASKS" cmd 可能更方便
    if if_use_my_launcher:
        # 方案A1：用双引号包裹。该脚本运行在计算节点的 Slurm 作业中，此刻 SLURM_NTASKS
        # 已由 Slurm 设好，于是在 export 这一刻就把它展开成真实核数，直接烤进 MY_LAUNCHER
        # 的值（例如 'srun -n 16'）。消费端（如 pei_vasp_univ_sbatch）拿到的已是现成数字，
        # 无需再做二次展开 / eval。注意不能用单引号，否则 $SLURM_NTASKS 会被原样保存。
        line_launcher = f'export MY_LAUNCHER="{line_launcher_1}"\n{line_launcher_2}'
    else:
        # 直接写入分支：该行在作业里执行，运行时 $SLURM_NTASKS 同样会展开。
        line_launcher = f"{line_launcher_1}  {line_launcher_2}"
    return line_launcher

def generate_slurm_script_base(partition: str, nodes: int, ncores: int, module_profile_type: str, MODULE_BLOCKS: dict[str, str],
                        launcher: str, cmd: str, if_use_my_launcher: bool,
                        if_output: bool = True, path_save: Path = Path('./sub_slurm_univ.sh')):

    line_header = generate_script_header(partition, nodes, ncores, module_profile_type, MODULE_BLOCKS)
    line_launcher = generate_launcher_command(launcher, cmd, if_use_my_launcher)
    line_myheader = (
        "# Auto-generated by pei_slurm_univ_submit (base job script). Do not edit by hand.\n"
        "# 该脚本由程序自动生成，每次运行都会被覆盖。\n"
    )
    line = line_header + "\n\n" + line_myheader + "\n\n" + line_launcher + "\n"

    if if_output:
        with open(path_save, 'w') as f:
            f.write(line)

    return line

def generate_slurm_script_sequential(partition: str, nodes: int, ncores: int, module_profile_type: str, MODULE_BLOCKS: dict[str, str],
                        launcher: str, cmd: str, if_use_my_launcher: bool,
                        group: list, mode: str,
                        if_output: bool = True, path_save: Path = Path('./sub_slurm_each_subdir.sh')):
    line_header = generate_script_header(partition, nodes, ncores, module_profile_type, MODULE_BLOCKS)
    line_launcher = generate_launcher_command(launcher, cmd, if_use_my_launcher)
    line_myheader = (
        f"# Auto-generated by pei_slurm_univ_submit ({mode} job script). Do not edit by hand.\n"
        "# 该脚本由程序自动生成，每次运行都会被覆盖。\n"
    )
    line_loop = generate_loop(group, mode, line_launcher)
    line = line_header + "\n\n" + line_myheader + "\n\n" + line_loop

    if if_output:
        with open(path_save, 'w') as f:
            f.write(line)

    return line

def generate_loop(group: list, mode: str, line_launcher: str):
    # subdir 已经是绝对路径了，在 get_lsubdir 中检查过了。
    # 用普通字符串拼接（而非 f-string）来写 bash，避免 $((...)) / ${...} 的花括号
    # 被 Python 当成替换字段；只在注入 Python 值（subdirs / mode / line_launcher）处用 +。
    group = [str(subdir) for subdir in group]
    subdirs = " ".join(group)

    # —— 计数器 + 失败/未收敛目录数组 + 目录列表 + 循环开头 ——
    line_loop = (
        'start_dir="$(pwd)"\n'
        "submit_success=0\n"
        "submit_failed=0\n"
        "submit_success_convergenced=0\n"
        "submit_success_not_convergenced=0\n"
        "failed_dirs=()\n"
        "not_convergenced_dirs=()\n"
        "lsubdir=(" + subdirs + " )\n"
        "\n"
        'for subdir in "${lsubdir[@]}"; do\n'
        '    cd "$start_dir" || exit 1\n'
        '    echo ""\n'
        '    echo "================ 📁 $subdir"\n'
        '    if ! cd "$subdir"; then\n'
        '        echo "❌ ERROR: 无法进入目录: $subdir" >&2\n'
        '        submit_failed=$((submit_failed + 1)); failed_dirs+=("$subdir")\n'
        "        continue\n"
        "    fi\n"
        '    echo "📍 当前目录: $(pwd)"\n'
    )

    if mode == "each-subdir":
        # 子作业经 sbatch --wait 提交：先看是否真的提交成功（输出含 Submitted batch job），
        # 提交成功后用 --wait 返回的退出码判断收敛。
        line_loop += (
            '    echo "▶️  sbatch --wait sub_slurm_univ.sh"\n'
            '    sbatch_out="$(sbatch --wait sub_slurm_univ.sh 2>&1)"; status=$?\n'
            '    echo "$sbatch_out"\n'
            '    if ! grep -q "Submitted batch job" <<< "$sbatch_out"; then\n'
            '        echo "❌ 提交失败: $subdir" >&2\n'
            '        submit_failed=$((submit_failed + 1)); failed_dirs+=("$subdir")\n'
            "        continue\n"
            "    fi\n"
            "    submit_success=$((submit_success + 1))\n"
        )
    elif mode == "single-alloc":
        # 单一分配内直接运行命令：cd 成功即视为运行成功，再按退出码判断收敛。
        line_loop += (
            '    echo "▶️  run (single-alloc)"\n'
            + textwrap.indent(line_launcher, "    ") + "\n"
            "    status=$?\n"
            "    submit_success=$((submit_success + 1))\n"
        )

    # —— 依据退出码判定收敛：pei_vasp_univ_sbatch 约定 0/10=已收敛，其余=未收敛 ——
    line_loop += (
        "    if (( status == 0 || status == 10 )); then\n"
        '        echo "✅ 已收敛 (exit $status)"\n'
        "        submit_success_convergenced=$((submit_success_convergenced + 1))\n"
        "    else\n"
        '        echo "❌ 未收敛 (exit $status): $subdir" >&2\n'
        "        submit_success_not_convergenced=$((submit_success_not_convergenced + 1))\n"
        '        not_convergenced_dirs+=("$subdir")\n'
        "    fi\n"
        "done\n"
    )

    # —— 最终 summary：四个量 + 挨个列出 not_convergenced_dirs 与 failed_dirs ——
    line_loop += (
        'cd "$start_dir" || exit 1\n'
        'echo ""\n'
        'echo "================ 📊 Summary (mode=' + mode + ')"\n'
        'echo "submit_success=$submit_success    submit_failed=$submit_failed'
        "    convergenced=$submit_success_convergenced"
        '    not_convergenced=$submit_success_not_convergenced"\n'
        "if (( ${#not_convergenced_dirs[@]} > 0 )); then\n"
        '    echo "❌ 未收敛的目录:"\n'
        '    for d in "${not_convergenced_dirs[@]}"; do echo "  - 📁 $d"; done\n'
        "fi\n"
        "if (( ${#failed_dirs[@]} > 0 )); then\n"
        '    echo "❌ 提交/运行失败的目录:"\n'
        '    for d in "${failed_dirs[@]}"; do echo "  - 📁 $d"; done\n'
        "fi\n"
        "if (( submit_failed > 0 || submit_success_not_convergenced > 0 )); then\n"
        '    echo "❌ Done: 存在失败或未收敛的计算。"\n'
        "    exit 1\n"
        "fi\n"
        'echo "🎉 Done: 全部完成且收敛！"\n'
        "exit 0\n"
    )
    return line_loop


# prepare parts
def get_lsubdir(lsubdir: list[str] = None, dir_root: Path = None):

    # 如果用户没指定
    if lsubdir is None or len(lsubdir) == 0 :
        if not dir_root.is_dir():
            fail(f"dir_root {dir_root} is not a directory")
        lsubdir = sorted([d for d in dir_root.iterdir() if d.is_dir()])
        if len(lsubdir) == 0:
            fail(f"No subdirectories found in dir_root {dir_root}")
    # 如果用户指定了 list[str]，逐个检查 basename 后拼到 dir_root 下
    else:
        for subdir in lsubdir:
            check_basename(subdir)
        lsubdir = [dir_root / Path(subdir) for subdir in lsubdir]

    # 检查是不是绝对路径，这很重要
    for subdir in lsubdir:
        if not subdir.is_dir():
            fail(f"subdir {subdir} is not a directory")
        check_absolute_path(subdir)

    return lsubdir

def split_chunks(chunks, lsubdir):
    total = len(lsubdir)
    if total == 0:
        fail("split_chunks: no directories to split")
    if chunks < 1:
        fail("split_chunks: chunk count must be >= 1 (got %d)" % chunks)
    if chunks > total:
        fail("--chunks (%d) cannot exceed number of job directories (%d)" % (chunks, total))
    base, rem = divmod(total, chunks)
    lgroup = []
    offset = 0
    num_check = 0
    for c in range(1, chunks + 1):
        count = base + (1 if c <= rem else 0)
        group = [str(d) for d in lsubdir[offset:offset + count]]
        lgroup.append(group)
        num_check += len(group)
        offset += count
    if np.abs(num_check - total) > 1e-10:
        fail("split_chunks: internal error: num_check %d != total %d" % (num_check, total))
    return lgroup

# Check part
# True means pass, False means fail
def check_positive_int(value, name):
    value = str(value)
    _DIGITS = set(string.digits) # {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}
    # 确认没负号，小数点，或其他非数字字符；同时确保第一个字符不是 '0'（除非值本身是 '0'，但这里不允许 '0' 作为正整数）。
    if value and value[0] in "123456789" and all(c in _DIGITS for c in value):
        return int(value)
    fail(f"%s must be a positive integer: %s" % (name, value if value else "<unset>"))

def check_none(value, name):
    if value is not None:
        return value
    fail(f"%s 参数不能为空" % name)

def check_basename(value):
    if "/" in value or "\\" in value:
        fail(f"目录名称 {value} 不能包含路径分隔符")
    return value

def check_absolute_path(value):
    if not Path(value).is_absolute():
        fail(f"必须是绝对路径: {value}")
    return value

# main body
def pei_slurm_univ_submit(
                    path_root: Path = None,
                    # 运行的基本模式
                    mode: str = None,
                    dir_root: Path = Path('./dir'),
                    lsubdir: str = None,
                    chunks: int = 1,
                    # script 相关参数
                    module_profile_type: str = None,
                    launcher_type: str = None,
                    cmd: str = None,
                    if_use_my_launcher: bool = False,  # 如果打开，将通过定义 MY_LAUNCHER 环境变量来传递 launcher_type，而不是直接在脚本中写死例如 srun -n "$SLURM_NTASKS" cmd
                    # 作业资源参数
                    partition: str = None,
                    nodes: int = None,
                    ncores: int = None,
                    # check markers dict
                    if_sbatch: bool = False,

                    # work_dir_name, dry_run, show_script, skip_if_file_contains

                    # global variables
                    MODULE_BLOCKS: dict[str, str] = {
                        "none": "# module-profile: none (no environment modules loaded)",
                        "zcm6-vasp": (
                            "# module-profile: zcm6-vasp  (VASP 5.4.4)\n"
                            "source /public3/soft/modules/module.sh\n"
                            "module load mpi/intel/17.0.7-thc\n"
                            'export PATH="/public3/home/scg6928/mysoft/vasp/vasp/544-yin/vasp.5.4.4.pl2/bin:$PATH"\n'
                        ),
                        "zcm6-lammps": (
                            "# module-profile: zcm6-lammps  (LAMMPS)\n"
                            "source /public3/soft/modules/module.sh\n"
                            "# TODO(zcm6-lammps): load the LAMMPS module(s) for this cluster and/or prepend the\n"
                            "#   LAMMPS bin dir to PATH. The exact module name is not known from this project,\n"
                            "#   so it is intentionally left blank — fill in before using this profile, e.g.:\n"
                            "#     module load mpi/intel/17.0.7-thc\n"
                            "#     module load lammps/<version>\n"
                            '#     export PATH="/path/to/lammps/bin:$PATH"\n'
                        ),
                        "zcm6-n2p2": (
                            "# module-profile: zcm6-n2p2  (n2p2)\n"
                            "source /public3/soft/modules/module.sh\n"
                            "module load eigen/3.8.8-cyc\n"
                            "module load gsl/2.5-cjj\n"
                            "module load mpi/openmpi/2.0.4-gcc-4.9.0\n"
                            'export PATH="/public3/home/scg6928/mysoft/tools/n2p2/2.3.0/n2p2-2.3.0/bin:$PATH"\n'
                        ),
                    },
                    LAUNCHERS: list = ["srun", "mpirun", "none"],
                    MODES: list = ["parallel", "each-subdir", "single-alloc"],

                    ):

    """

    Args:
        path_root (Path): 根目录路径，默认为当前目录。保险起见应该全部由外部导入
        mode (str): 运行模式，必须是 "parallel"、"each-subdir" 或 "single-alloc" 之一。
        dir_root (Path): 根目录路径，默认为当前目录下的 "dir"。
        lsubdir (list): 一级子目录列表，默认为 None。必须处于dir_root下。
        chunks (int): 将作业目录分成多少块，默认为 1。
    """

    ################################### Check
    # check if None
    for temp_value, temp_name in [(path_root, "path_root"), (mode, "mode"), (module_profile_type, "module_profile_type"),
                                  (launcher_type, "launcher_type"), (cmd, "cmd"), (partition, "partition"),
                                  (chunks, "chunks"), (nodes, "nodes"), (ncores, "ncores")]:
        check_none(temp_value, temp_name)

    # path_root是一切的根基，必须是绝对路径
    check_absolute_path(path_root)

    # check if positive int（必须接住返回值，把字符串等输入强制转成 int，
    # 否则后续 split_chunks 的 chunks < 1 / divmod 会因类型不符而报错）
    chunks = check_positive_int(chunks, "chunks")
    nodes = check_positive_int(nodes, "nodes")
    ncores = check_positive_int(ncores, "ncores")

    # check mode
    if mode not in MODES:
        fail(f"Unknown mode: {mode}")

    # check module_profile_type
    if module_profile_type not in list(MODULE_BLOCKS.keys()):
        fail(f"Unknown module profile type: {module_profile_type}")

    # check launcher_type
    if launcher_type not in LAUNCHERS:
        fail(f"Unknown launcher type: {launcher_type}")
    ################################### Check to here

    os.chdir(path_root)
    print(f"path_root: {path_root}")

    # 把当前路径全部转化为绝对路径
    dir_root = path_root / dir_root

    ################################### Prepare
    # get lsubdir
    lsubdir = get_lsubdir(lsubdir, dir_root) # 已经被检查了确认都存在文件夹
    lgroup = split_chunks(chunks, lsubdir)
    ################################### Prepare to here

    ################################### Main control flow
    # 不使用check_file_contain参数，这是在cmd里应该执行的，而非提前去检查

    # 提前生成所需的base slurm script
    if mode in ["parallel", "each-subdir"]:
        for subdir in lsubdir:
            path_save = subdir / "sub_slurm_univ.sh"
            generate_slurm_script_base(partition, nodes, ncores, module_profile_type, MODULE_BLOCKS,
                                        launcher_type, cmd, if_use_my_launcher,
                                        if_output=True, path_save=path_save)

    if mode == "parallel":
        if chunks > 1:
            warn("--chunks ignored in parallel mode (already one job per dir)")
        if if_sbatch:
            # parallel 只负责提交、不等待结果，因此只统计 submit_success / submit_failed。
            submit_success = 0
            submit_failed = 0
            submit_failed_dirs = []
            for subdir in lsubdir:
                path_save = subdir / "sub_slurm_univ.sh"
                print("")
                print(f"================ 📁 {subdir}")
                print(f"▶️  sbatch {path_save}")
                # 这个 bash 脚本结束就会回到 path_root
                rc = os.system(f"cd {subdir} && sbatch {path_save}")
                exit_code = os.waitstatus_to_exitcode(rc)
                if exit_code == 0:
                    print("✅ 提交成功")
                    submit_success += 1
                else:
                    print(f"❌ 提交失败 (exit {exit_code}): {subdir}")
                    submit_failed += 1
                    submit_failed_dirs.append(subdir)
            # —— summary：两个量 + 挨个列出 submit_failed_dirs ——
            print("")
            print("================ 📊 Summary (mode=parallel)")
            print(f"submit_success={submit_success}    submit_failed={submit_failed}")
            if submit_failed_dirs:
                print("❌ 提交失败的目录:")
                for d in submit_failed_dirs:
                    print(f"  - 📁 {d}")
            print("❌ Done with submission failures." if submit_failed > 0 else "🎉 Done!")
    elif mode in ["each-subdir", "single-alloc"]:
        # each-subdir 的 chunk 脚本只负责循环 + sbatch --wait 子作业，本身不跑计算，
        # 实际计算资源由各子 base 脚本申请，因此编排脚本固定为 -N 1 -n 1。
        if mode == "each-subdir" and (nodes != 1 or ncores != 1):
            warn(f"each-subdir 编排脚本无需多资源，已将 nodes={nodes}, ncores={ncores} 修正为 1")
            nodes = 1
            ncores = 1
        # 这里你应该提前在所有subdir中生成base script, 因为 slurm script 中无法调用generate_base() 函数
        for id, group in enumerate(lgroup, start = 1):
            path_save = path_root / f"sub_slurm_{mode.replace('-', '_')}_chunk{id:03d}.sh"
            generate_slurm_script_sequential(partition, nodes, ncores, module_profile_type, MODULE_BLOCKS,
                                            launcher_type, cmd, if_use_my_launcher,
                                            group=group, mode=mode,
                                            if_output=True, path_save=path_save)
            if if_sbatch:
                os.system(f"cd {path_root} && sbatch {path_save}")

    ################################### Main control flow to here
    return None

test_args1 = {
    "path_root": Path('/public3/home/scg6928/mywork/test-sbatch/y_E_in_1_2_bulk'),
    "mode": "parallel",
    "dir_root": Path('./y_dir'),
    "lsubdir": [],
    "chunks": 5,
    "module_profile_type": "zcm6-vasp",
    "launcher_type": "srun",
    "cmd": "echo Hello, World!",
    "partition": "amd_512",
    "nodes": 2,
    "ncores": 16,}

test_args2 = {
    "path_root": Path('/public3/home/scg6928/mywork/test-sbatch/y_E_in_1_2_bulk'),
    "mode": "each-subdir",
    "dir_root": Path('./y_dir'),
    "lsubdir": [],
    "chunks": 5,
    "module_profile_type": "zcm6-vasp",
    "launcher_type": "srun",
    "cmd": "pei_vasp_univ_sbatch",
    "partition": "amd_512",
    "nodes": 2,
    "ncores": 16,}

test_args3 = {
    "path_root": Path('/public3/home/scg6928/mywork/test-sbatch/y_E_in_1_2_bulk'),
    "mode": "single-alloc",
    "dir_root": Path('./y_dir'),
    "lsubdir": [],
    "chunks": 5,
    "module_profile_type": "zcm6-vasp",
    "launcher_type": "srun",
    "cmd": "pei_vasp_univ_sbatch",
    "partition": "amd_512",
    "nodes": 2,
    "ncores": 16,}


# 列举三种测试环境
# pei_slurm_univ_submit(**test_args1 )
pei_slurm_univ_submit(**test_args2 )
pei_slurm_univ_submit(**test_args3 )