#!/bin/bash


duration=$1
echo -e "\nelapsed time (second):" $duration

h1=`echo $(( $duration / 3600 ))`
m1=`echo $(( ($duration % 3600) / 60 ))`
s1=`echo $(( ($duration % 3600) % 60 ))`

echo -e "$h1 h : $m1 m : $s1 s \n"

