#!/bin/bash
# B. Yin, 2022-03-18


main(){
    srcdir0=y_full_relax

    if [ -d "$srcdir0" ]
    then
        sub_run_E_in_1_bulk $1
    else
        echo "==> no $srcdir0 found! Abort!"
        exit
    fi
}





sub_run_E_in_1_bulk(){
    srcdir=`pwd`/y_full_relax_temp
    rm -rf $srcdir

    cp -r $srcdir0  $srcdir 
    cd $srcdir


    myfile=./CONTCAR 
    if [ -f "$myfile" ]; then
        echo "$myfile exists."
    else 
        echo "$myfile does not exist. cp POSCAR CONTCAR "
        cp POSCAR CONTCAR
    fi


#    yin_vasp_univ_find_and_change  -isym  0 
    yin_vasp_univ_find_and_change  -isif  3

    yin_slurm_find_and_change  -srpl  H
 
    cd ..


    
    #--------------------   

    a1=`sed -n '3,3p' $srcdir/CONTCAR | awk '{printf "%.16f", $1}'`
    a2=`sed -n '3,3p' $srcdir/CONTCAR | awk '{printf "%.16f", $2}'`
    a3=`sed -n '3,3p' $srcdir/CONTCAR | awk '{printf "%.16f", $3}'`
    
    b1=`sed -n '4,4p' $srcdir/CONTCAR | awk '{printf "%.16f", $1}'`
    b2=`sed -n '4,4p' $srcdir/CONTCAR | awk '{printf "%.16f", $2}'`
    b3=`sed -n '4,4p' $srcdir/CONTCAR | awk '{printf "%.16f", $3}'`
    
    c1=`sed -n '5,5p' $srcdir/CONTCAR | awk '{printf "%.16f", $1}'`
    c2=`sed -n '5,5p' $srcdir/CONTCAR | awk '{printf "%.16f", $2}'`
    c3=`sed -n '5,5p' $srcdir/CONTCAR | awk '{printf "%.16f", $3}'`
    
    echo $a1 $a2 $a3
    echo $b1 $b2 $b3
    echo $c1 $c2 $c3

    
    #=====================
    
    dirCij=y_E_in_1_bulk
    
    rm -rI  $dirCij
    mkdir   $dirCij
    cd      $dirCij
    
    mkdir y_dir
    cd    y_dir
    
    #=====================
   

    case "$1" in
        -large) echo "==> de=0.005 "
            de=0.005
            ;;
        *)      echo "==> de=0.001 "
            de=0.001
            ;;
    esac



    for i1 in  -3  -2  -1  0  1  2  3  ; do

        el=`echo "scale=16; $i1*$de+1" | bc`  

        dirn=`printf "%.3f" "$el"`
        echo ================ $dirn
        mkdir $dirn
        cd $dirn

        cp $srcdir/{INCAR,KPOINTS,CONTCAR,POTCAR,sub.*,Y_*,CHGCAR} ./
        mv CONTCAR POSCAR


        a11=`echo "scale=16; $a1*$el" | bc`
        b11=`echo "scale=16; $b1*$el" | bc`
        c11=`echo "scale=16; $c1*$el" | bc`

        latta=`printf "%.16f  %.16f  %.16f"   "$a11" "$a2" "$a3"`
        lattb=`printf "%.16f  %.16f  %.16f"   "$b11" "$b2" "$b3"`
        lattc=`printf "%.16f  %.16f  %.16f"   "$c11" "$c2" "$c3"`

        echo -e " "$latta "\n" $lattb "\n" $lattc

        sed '3s/.*/'"$latta"'/' ./POSCAR > ./temp1
        sed '4s/.*/'"$lattb"'/' ./temp1 > ./temp2
        sed '5s/.*/'"$lattc"'/' ./temp2 > ./POSCAR
        rm ./temp*
    


        echo -e "356\n0.0  0.0  0.0  0.0  0.0  0.0" > Y_CONSTR_CELL.IN


        echo 'submit dir:' `pwd`
        sbatch sub.*
        cd ..

    done


    rm -rf $srcdir
}



main "$@"; exit




