#!/bin/bash

###################### For GSFE:
# os.system("echo -e '3\n0.0  0.0  0.0  0.0  0.0  0.0' > Y_CONSTR_LATT")
# os.system("yin_vasp_univ_find_and_change -isif 3")
# # fix x, y scaled coordinates
# atoms = read("POSCAR", format="vasp")
# c = FixScaled(cell=atoms.get_cell(), a=range(0, len(atoms)), mask=[True, True, False])
# atoms.set_constraint(c)
# write("POSCAR", atoms, format="vasp")

###################### For SSF:
# os.system("echo -e '356\n0.0  0.0  0.0  0.0  0.0  0.0' > Y_CONSTR_LATT")
# os.system("yin_vasp_univ_find_and_change -isif 3")
# # fix x, y scaled coordinates
# atoms = read("POSCAR", format="vasp")
# c = FixScaled(cell=atoms.get_cell(), a=range(0, len(atoms)), mask=[False, False, False])
# atoms.set_constraint(c)
# write("POSCAR", atoms, format="vasp")

# ---------- Colors ----------
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ---------- Help ----------
# The slip mode picks the Burgers direction (bp1, bp2 in units of a1, b2) that the top
# of the cell is sheared along; keep this list in sync with the case block below.
print_help(){
    echo -e "${GREEN}pei_vasp_run_gsfe${NC} - Generalized stacking fault energy (GSFE) curve"
    echo ""
    echo -e "${YELLOW}Usage:${NC}"
    echo -e "  $(basename "$0") ${GREEN}<slip_mode>${NC}"
    echo ""
    echo -e "${YELLOW}Slip modes:${NC}    (output dir, shear vector in units of a1 / b2)"
    echo -e "  ${GREEN}-FCC_111${NC}       y_gsfe_FCC_111       -0.5,  1/3   full <112> path"
    echo -e "  ${GREEN}-FCC_100${NC}       y_gsfe_FCC_100        0.5,  0.5"
    echo -e "  ${GREEN}-HCP_basal${NC}     y_gsfe_HCP_basal     -0.5,  1/3"
    echo -e "  ${GREEN}-HCP_prism1w${NC}   y_gsfe_HCP_prism1w    0.5,  0.0"
    echo -e "  ${GREEN}-HCP_pyr1n${NC}     y_gsfe_HCP_pyr1n      0.5, -0.11"
    echo -e "  ${GREEN}-HCP_pyr1w${NC}     y_gsfe_HCP_pyr1w      0.0,  0.5"
    echo -e "  ${GREEN}-HCP_pyr2${NC}      y_gsfe_HCP_pyr2       0.0,  0.5"
    echo -e "  ${GREEN}-a1${NC}            y_gsfe_a1             1.0,  0.0   full a1 period"
    echo ""
    echo -e "${YELLOW}Notes:${NC}"
    echo -e "  - Run it at the level of ${BLUE}y_full_relax${NC}; the source POSCAR must be ${BLUE}Cartesian${NC}."
    echo -e "  - Prepare y_full_relax first with ${GREEN}pei_vasp_univ_gsfe_preliminary${NC}"
    echo -e "    (ISYM=1, Cartesian POSCAR, selective dynamics, Y_CONSTR_LATT=3)."
    echo -e "  - Makes ${GREEN}N1+1 = 11${NC} images in <workdir>/y_dir/00..10 and does ${YELLOW}NOT${NC} sbatch;"
    echo -e "    submit them yourself, then post-process."
    echo ""
    echo -e "${YELLOW}Example:${NC}"
    echo -e "  $(basename "$0") -FCC_111        # the usual FCC <112> gamma-surface line"
    echo -e "  $(basename "$0") -HCP_basal      # HCP basal slip"
    echo ""
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    print_help
    exit 0
fi

if [ -z "$1" ]; then      # empty is true
    echo -e "==>  Please indicate which GSFE to compute. Abort!  (see ${GREEN}$(basename "$0") --help${NC})"
    exit
fi

cat << 'EOF'
For GSFE:

os.system("echo -e '3\n0.0  0.0  0.0  0.0  0.0  0.0' > Y_CONSTR_LATT")
os.system("yin_vasp_univ_find_and_change -isif 3")

# fix x, y scaled coordinates
atoms = read("POSCAR", format="vasp")
c = FixScaled(cell=atoms.get_cell(), a=range(0, len(atoms)), mask=[True, True, False])
atoms.set_constraint(c)
write("POSCAR", atoms, format="vasp")
EOF


srcdir=`pwd`/y_full_relax

a1=`sed -n '3,3p' $srcdir/POSCAR | awk '{printf "%.16f", $1}'`

b2=`sed -n '4,4p' $srcdir/POSCAR | awk '{printf "%.16f", $2}'`

c1=`sed -n '5,5p' $srcdir/POSCAR | awk '{printf "%.16f", $1}'`
c2=`sed -n '5,5p' $srcdir/POSCAR | awk '{printf "%.16f", $2}'`
c3=`sed -n '5,5p' $srcdir/POSCAR | awk '{printf "%.16f", $3}'`

echo $a1 
echo $b2 
echo $c1 $c2 $c3



case "$1" in
    -HCP_basal) echo "==> run GSFE for HCP_basal: "
        workdir=y_gsfe_HCP_basal               
        N1=10
        bp1=-0.5 
        bp2=`echo "scale=16;  1.0/3.0" | bc`                 
        ;;
   

    -HCP_prism1w) echo "==> run GSFE for HCP_prism1w: "
        workdir=y_gsfe_HCP_prism1w
        N1=10
        bp1=0.5
        bp2=0.0 
        ;;


    -HCP_pyr1n) echo "==> run GSFE for HCP_pyr1n: "
        workdir=y_gsfe_HCP_pyr1n
        N1=10
        bp1=0.5
        bp2=-0.11
        ;;


    -HCP_pyr1w) echo "==> run GSFE for HCP_pyr1w: "
        workdir=y_gsfe_HCP_pyr1w
        N1=10
        bp1=0.0
        bp2=0.5
        ;;


    -HCP_pyr2) echo "==> run GSFE for HCP_pyr2: "
        workdir=y_gsfe_HCP_pyr2
        N1=10
        bp1=0.0
        bp2=0.5
        ;;


    -FCC_111) echo "==> run GSFE for FCC_111: "
        workdir=y_gsfe_FCC_111
        N1=10
        bp1=-0.5 
        bp2=`echo "scale=16;  1.0/3.0" | bc`   
        ;;


    -FCC_100) echo "==> run GSFE for FCC_100: "
        workdir=y_gsfe_FCC_100
        N1=10
        bp1=0.5
        bp2=0.5
        ;;


    -a1) echo "==> run GSFE for a1: "
        workdir=y_gsfe_a1
        N1=10
        bp1=1.0
        bp2=0.0
        ;;


 
    *)  echo -e "==>  Option $1 not recognized. Abort!  (see ${GREEN}$(basename "$0") --help${NC})"
        exit
        ;;
esac

echo "bp1, bp2:"  $bp1  $bp2


#========================


da31=`echo "scale=16;  $a1 * $bp1" | bc`
da32=`echo "scale=16;  $b2 * $bp2" | bc`


rm -rI $workdir
mkdir  $workdir
cd     $workdir

mkdir  y_dir
cd     y_dir


for ((i1=0; i1<=$N1; i1=i1+1)) ;  do
    dirn1=`printf "%02d" "$i1"`
    mkdir $dirn1
    cd $dirn1
    
    echo '====================' $dirn1
    cp $srcdir/{INCAR,KPOINTS,POSCAR,POTCAR,sub.*,Y_*,CHGCAR} ./
    
    c1_new=`echo "scale=16; $c1+ $da31 *($i1/$N1)" | bc`
    c2_new=`echo "scale=16; $c2+ $da32 *($i1/$N1)" | bc`
    
    data1=`printf "    %.16f    %.16f    %.16f" "$c1_new" "$c2_new" "$c3"`
    echo $data1
    
    sed '5s/.*/'"$data1"'/' ./POSCAR > ./temp
    mv temp POSCAR
    
    echo 'submit dir:' `pwd`
    #sbatch sub.*
    
    cd ..
done




