#!/bin/bash
# B. Yin


if [ "$#" -eq 0 ]; then
    echo "==>  Please indicate the tag to modify. Abort!"
    exit 1
fi

if [ "$#" -lt 2 ] || [ $(( $# % 2 )) -ne 0 ]; then
    echo "==>  Please provide option/value pairs, for example: -nbands 18 -algo Normal. Abort!"
    exit 1
fi

# For INCAR tag changes, "comment" only comments the existing matched line.
# Use "comment:value" to rewrite the tag with value and keep it commented.
# Multiple option/value pairs are validated together, then applied from left to right.
# INCAR tags without a dedicated case are accepted as -tag_name and written in uppercase.
script_path=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "$script_path")
tag_help_file="${script_dir}/incar_tag_help_vaspwiki.tsv"


get_tag_help(){
    local tag1=$1
    local lookup_tag=$tag1
    local tag_help

    # These Wiki entries describe numbered tag families rather than literal keys.
    case "$tag1" in
        IMAGE_[0-9]*) lookup_tag="IMAGE_1" ;;
        LIBXC1_P[0-9]*) lookup_tag="LIBXC1_PN" ;;
        LIBXC2_P[0-9]*) lookup_tag="LIBXC2_PN" ;;
        XC[0-9]*_P[0-9]*) lookup_tag="XCM_PN" ;;
    esac

    if [ -f "$tag_help_file" ]; then
        tag_help=$(awk -F '\t' -v tag="$lookup_tag" '$1 == tag {print $2; exit}' "$tag_help_file")
    fi
    if [ -z "$tag_help" ]; then
        tag_help="VASP INCAR tag; verify spelling and options in VASP Wiki"
    fi
    printf '%s' "$tag_help"
}


check_option_pair(){
    local option=$1
    local raw_value=$2
    local raw_tag

    if [ -z "$raw_value" ]; then
        echo "==>  Empty value for option $option. Abort!"
        return 1
    fi
    case "$option" in
        -*)
            raw_tag=${option#-}
            case "$raw_tag" in
                ""|*[!A-Za-z0-9_/]*)
                    echo "==>  Invalid option $option. Use letters, numbers, '_', or '/'. Abort!"
                    return 1
                    ;;
            esac
            ;;
        *)
            echo "==>  Option $option must start with '-'. Abort!"
            return 1
            ;;
    esac
}


replace_line(){
    local file_path=$1
    local line_number=$2
    local replacement=$3
    local temp_path

    temp_path=$(mktemp "${file_path}.pei_tmp.XXXXXX") || return 1
    if ! {
        head -n "$((line_number - 1))" "$file_path"
        printf '%s\n' "$replacement"
        tail -n "+$((line_number + 1))" "$file_path"
    } > "$temp_path"; then
        rm "$temp_path"
        return 1
    fi
    chmod --reference="$file_path" "$temp_path" || return 1
    mv "$temp_path" "$file_path"
}



sub_change(){
    local file1=$1
    local tag1=$2
    local str1=$3
    local filen
    local j1

    if [ "$comment_mode" = "rewrite" ]; then
        if ! echo "$str1" | grep -q -E "^[[:space:]]*#"; then
            str1="#$str1"
        fi
    fi

    if [ "$comment_mode" = "keep" ]; then
        echo "==> commenting '"$tag1"' in '"$file1"': "
    else
        echo "==> changing '"$tag1"' in '"$file1"' to '"$str1"': "
    fi

    for filen in `find ./ -type f -name $file1`; do
        #echo $filen
        # Be aware that VASP will use the first occurrence. https://www.vasp.at/forum/viewtopic.php?t=19227
        j1=`grep -n -E "^[[:space:]]*#*[[:space:]]*${tag1}[[:space:]]*=" "$filen" | head -1 | cut -d ":" -f1`
        echo $j1
        if [ "$comment_mode" != "keep" ]; then
            echo $str1
        fi
        if [ "$j1" = "" ]; then
            if [ "$comment_mode" = "keep" ]; then
                echo "no $tag1 in the file; nothing to comment"
            else
                # Keep the appended tag on its own line even if INCAR lacks a final newline.
                if [ -s "$filen" ] && [ "$(tail -c 1 "$filen" | od -An -t u1 | tr -d '[:space:]')" != "10" ]; then
                    printf '\n' >> "$filen"
                fi
                printf '%s\n' "$str1" >> "$filen"
                echo "added $tag1 to $filen"
            fi
        else
            if [ "$comment_mode" = "keep" ]; then
                if sed -n "${j1}p" "$filen" | grep -q -E "^[[:space:]]*#"; then
                    echo "already commented"
                else
                    str1="#$(sed -n "${j1}p" "$filen")"
                    replace_line "$filen" "$j1" "$str1" || exit 1
                fi
            else
                replace_line "$filen" "$j1" "$str1" || exit 1
            fi
        fi
    done
}








process_option(){
    local comment_mode="none"
    local value1=$2
    local str
    local tag1
    local tag_help

    if [ "$2" = "comment" ]; then
        comment_mode="keep"
        value1=""
    elif [[ "$2" == comment:* ]]; then
        comment_mode="rewrite"
        value1=${2#comment:}
    fi

case "$1" in

    -a0) 
        echo "==> changing a0 in POSCAR to" $2 ": "
        for filen in ` find ./ -type f -name "POSCAR" `; do
            echo $filen 
            sed '2s/.*/'" $2"'/' $filen > temp
            mv temp $filen
        done
        ;;



# the lattice a3  
    -a3) 
        echo "==> changing a3 in POSCAR to" $2 ": "
        for filen in ` find ./ -type f -name "POSCAR*" `; do
            echo $filen 
            sed '5s/.*/'" $2"'/' $filen > temp
            mv temp $filen
        done
        ;;



    -a0contcar)
        echo "==> changing a0 in CONTCAR to" $2 ": "
        for filen in ` find ./ -type f -name "CONTCAR*" `; do
            echo $filen
            sed '2s/.*/'" $2"'/' $filen > temp
            mv temp $filen
        done
        ;;



    -elem_d)
        echo "==> deleting element info in POSCAR: "
        for filen in ` find ./ -type f -name "POSCAR*" `; do
            echo $filen
            sed '6,6d' $filen > temp
            mv temp $filen
        done
        ;;



    -elem_i)
        echo "==> inserting element info" $2 "in POSCAR: "
        for filen in ` find ./ -type f -name "POSCAR*" `; do
            echo $filen
            sed '6i'" $2" $filen > temp
            mv temp $filen
        done
        ;;







    -cn)
        echo "==> changing cn in POSCAR to" $2 ": "
        for filen in ` find ./ -type f -name "POSCAR*" `; do
            echo $filen
            sed '6s/.*/'" $2"'/' $filen > temp
            mv temp $filen
        done
        ;;




    -kp)
        echo "==> changing kp in KPOINTS to" $2 ": "
        for filen in ` find ./ -type f -name "KPOINTS" `; do
            echo $filen
            sed '4s/.*/'" $2"'/' $filen > temp
            mv temp $filen
        done
        ;;




    -ispin) 
        str=" ISPIN= $value1      # 1=non; 2=spin "
        sub_change  INCAR  "ISPIN"  "$str" 
        ;;


    -isif) 
        str=" ISIF= $value1      # fix: 2=box; 3=none; 4=volume "
        sub_change  INCAR  "ISIF"  "$str"
        ;;


    -ediffg) 
        str=" EDIFFG= $value1      # -1E-3 "
        sub_change  INCAR  "EDIFFG"  "$str"
        ;;


    -ediff)
        str=" EDIFF= $value1      # 1E-6 "
        sub_change  INCAR  "EDIFF"  "$str"
        ;;


    -isym) 
        if [ "$value1" == "default" ]; then
            str="# ISYM= 0 " 
        else
            str=" ISYM= $value1      # 0=off "
        fi
        sub_change  INCAR  "ISYM"  "$str"
        ;;


    -nsw)
        str=" NSW= $value1      # ionic steps, 0=static "
        sub_change  INCAR  "NSW"  "$str"
        ;;


    -algo)
        str=" ALGO= $value1      # N=Normal, F=Fast "
        sub_change  INCAR  "ALGO"  "$str"
        ;;


    -ismear)
        str=" ISMEAR= $value1      # 1=1st order MP, -5=tetrahedron "
        sub_change  INCAR  "ISMEAR"  "$str"
        ;;


    -lreal)
        str=" LREAL= $value1      # F; A=Auto "
        sub_change  INCAR  "LREAL"  "$str"
        ;;


    -nelm)
        str=" NELM= $value1      # max e-steps "
        sub_change  INCAR  "NELM"  "$str"
        ;;


    -encut)
        str=" ENCUT= $value1      # plane wave cutoff "
        sub_change  INCAR  "ENCUT"  "$str"
        ;;


    -sigma)
        str=" SIGMA= $value1      # width of smearing "
        sub_change  INCAR  "SIGMA"  "$str"
        ;;


    -lorbit)
        str=" LORBIT= $value1      # 10=LDOS  11=PDOS "
        sub_change  INCAR  "LORBIT"  "$str"
        ;;


    -ibrion)
        str=" IBRION= $value1      # -1=no update  2=CG "
        sub_change  INCAR  "IBRION"  "$str"
        ;;


    -nedos)
        str=" NEDOS= $value1      # 301=default, 3000=dos, bs"
        sub_change  INCAR  "NEDOS"  "$str"
        ;;


    -icharg)
        str=" ICHARG= $value1      # 1=file; 11=dos, bs"
        sub_change  INCAR  "ICHARG"  "$str"
        ;;
    
    -lmaxmix)
        str=" LMAXMIX= $value1      # mix which l-quantum number"
        sub_change  INCAR  "LMAXMIX"  "$str"
        ;;


    -nbands)
        str=" NBANDS= $value1      # max: 0.5*NELEC+2*NIONS"
        sub_change  INCAR  "NBANDS"  "$str"
        ;;

    -lwave)
        str=" LWAVE= $value1      # write WAVECAR"
        sub_change  INCAR  "LWAVE"  "$str"
        ;;

    -lcharg)
        str=" LCHARG= $value1      # write CHGCAR"
        sub_change  INCAR  "LCHARG"  "$str"
        ;;

    -lelf)
        str=" LELF= $value1      # write electronic localiz. function (ELF), KPAR must be off"
        sub_change  INCAR  "LELF"  "$str"
        ;;

    -potim)
        str=" POTIM= $value1      # defeault 0.5. "
        sub_change  INCAR  "POTIM"  "$str"
        ;;

    -ncore)
        str=" NCORE= $value1      # parallelization over cores, 4"
        sub_change  INCAR  "NCORE"  "$str"
        ;;

    -npar)
        str=" NPAR= $value1      # parallelization over nodes, 8"
        sub_change  INCAR  "NPAR"  "$str"
        ;;

    -kpar)
        str=" KPAR= $value1      # parallelization over k-points, 4"
        sub_change  INCAR  "KPAR"  "$str"
        ;;

    -nsim)
        str=" NSIM= $value1      # parallelization over bands, 4"
        sub_change  INCAR  "NSIM"  "$str"
        ;;

    -*)
        tag1=${1#-}
        case "$tag1" in
            ""|*[!A-Za-z0-9_/]*)
                echo "==>  Invalid INCAR tag option $1. Use letters, numbers, '_', or '/'. Abort!"
                exit 1
                ;;
        esac
        tag1=$(printf '%s' "$tag1" | tr '[:lower:]' '[:upper:]')
        tag_help=$(get_tag_help "$tag1")
        str=" $tag1= $value1      # $tag_help"
        sub_change INCAR "$tag1" "$str"
        ;;

    *)  echo "==>  Option $1 not recognized. Abort!"
        exit 1
        ;;
esac
}


largs=("$@")

# Validate every pair before editing any file, so malformed trailing input cannot cause partial changes.
for ((index = 0; index < ${#largs[@]}; index += 2)); do
    check_option_pair "${largs[index]}" "${largs[index + 1]}" || exit 1
done

for ((index = 0; index < ${#largs[@]}; index += 2)); do
    process_option "${largs[index]}" "${largs[index + 1]}"
done
