#!/bin/bash
# only test

echo "🚀 ==> Resubmit unfinished jobs under y_dir sequentially"

for dir in ./y_dir/*/; do
    # ||, or operator to skip if cd fails
    cd "$dir" || continue  
    echo "================ 📁 $dir"
    echo "📍 Current dir: $(pwd)"
    

    tag_resub=F
    # Check if OUTCAR exists
    if [[ -f "OUTCAR" ]]; then
        # if "reached required accuracy" is found in OUTCAR, skip resubmission
        if grep -q "reached required accuracy" OUTCAR; then
            echo "✅ Calculation completed successfully, skipping..."
        # if not found, resubmit the job
        else
            echo "❌ Calculation not completed, resubmitting..."
            tag_resub=T
        fi
    else
        # if OUTCAR does not exist, resubmit the job
        echo "🔍 No OUTCAR found, resubmitting job..."
        tag_resub=T
    fi

    if [[ $tag_resub == "T" ]]; then
        cp CONTCAR POSCAR
        srun vasp_std
    fi
    
    # Now, we have the OUTCAR, and do double check
    if grep -q "reached required accuracy" OUTCAR; then
        echo "✅ Calculation completed successfully after resubmission."
    else
        echo "❌ Calculation still not completed after resubmission."
    fi

    cd - > /dev/null
    echo ""  # 空行分隔不同任务输出
done

echo "🎉 Done!"

