"""
gsfe post-processing submodule

This module provides functions to post-process generalized stacking fault energy (GSFE)
data from VASP or LAMMPS calculations, generate plots, and summarize results in formatted text files.

Functions:
    - post_gsfe: Main function to process GSFE data and generate outputs.
    - check_constraints: Verify structural constraints for GSFE calculations.
    - find_sf_usf: Identify local minima and maxima in GSFE data.
    - write_output: Write GSFE results to a formatted text file.
    - read_output: Read GSFE results from a text file generated by `write_output()`.
    - plot_GSFE: Plot GSFE energy curve, displacement, and shear stress evolution.

Change log:
    - Written by Binglun Yin on unkown time (https://github.com/BinglunYin/vasp_utils/blob/master/vasp_workflow_planar_defects/yin_vasp_plot_gsfe.py).
    - Modified by J. P. on 2025.11.04 to fit LAMMPS output.
"""
# This page is taken from https://github.com/BinglunYin/vasp_utils/blob/master/vasp_workflow_planar_defects/yin_vasp_plot_gsfe.py
# Changed to fit the lammps output by J. P. 
# 2025.11.04

# must be firstly imported
from __future__ import annotations

import numpy as np
from myvasp import vasp_func as vf 
import sys
from ase.io import read
import os
import matplotlib
import matplotlib.pyplot as plt
from mymetal.universal.plot.general import general_set_all_rcParams
from pathlib import Path
from typing import Union, Any, Dict, Optional, List
import re


def post_gsfe( post_data_path: str = None,
            latoms_path: str = None,
            latoms_format: str = 'lammps-dump-text',
            save_fig_path: str = './y_post_gsfe.pdf',
            save_u3_fig_path: str = './y_post_gsfe.u3.pdf',
            save_txt_path: str = './y_post_gsfe.txt',) -> None:
    """
    Post-process generalized stacking fault energy (GSFE) data from VASP or LAMMPS.

    This function reads post-calculation data and atomic configurations,
    checks for structural consistency, computes GSFE (γ-surface), and
    generates both plots and text reports.

    Args:
        post_data_path (str): Path to the VASP post data file (e.g., OUTCAR summary or parsed file).
        latoms_path (str): Path to atomic structure sequence (e.g., LAMMPS dump or trajectory).
        latoms_format (str, optional): ASE-supported format of atomic data. Defaults to 'lammps-dump-text'.
        save_fig_path (str, optional): Output path for GSFE plot. Defaults to './y_post_gsfe.pdf'.
        save_u3_fig_path (str, optional): Output path for displacement (u3) plot. Defaults to './y_post_gsfe.u3.pdf'.
        save_txt_path (str, optional): Output path for numerical results. Defaults to './y_post_gsfe.txt'.

    Returns:
        None
    """
    qe = vf.phy_const('qe')
    
    jobn, Etot, Eent, pres = vf.vasp_read_post_data(post_data_path)
    njobs = len(jobn)  # number of jobs

    if njobs < 1.5:
        sys.exit('==> ABORT! more structures needed. ')

    if abs(float(jobn[0])) > 1e-5 :
        sys.exit('==> ABORT! no reference state. ')
        
    latoms = read(latoms_path, format = latoms_format, index = ':')
    
    Asf = np.linalg.norm( \
        np.cross(latoms[0].cell[0, :], latoms[0].cell[1, :] ) )
    a11 = latoms[0].cell[0, 0]
    a22 = latoms[0].cell[1, 1]

    natoms = latoms[0].get_positions().shape[0]    
    E0bulk = Etot[0] / natoms


    dE, da3, dpos3 = check_constraints(Etot, latoms)
   
    gamma = dE/Asf *qe*1e23   
    sf, usf = find_sf_usf(gamma)

    from ase.formula import Formula
    str2 = latoms[0].get_chemical_formula()
    str2 = Formula(str2).format('latex')
    str_all = '%s\n$A =$%.4f $\\mathrm{\\AA}^2$' %(str2, Asf)  

    
    # #=========================
    plot_GSFE(jobn, gamma, da3, dpos3, latoms, str_all, save_fig_path, save_u3_fig_path)
    write_output(Asf, a11, a22, E0bulk, sf, usf, jobn, dE, gamma, da3, save_txt_path)

def check_constraints(Etot: list = None, latoms: list = None) -> tuple:
    """
    Check geometric and atomic constraints for GSFE calculations.

    Ensures that all structures in the sliding sequence:
      - Have identical atomic composition.
      - Maintain in-plane lattice constants (no relaxation in-plane).
      - Show displacement only along the slip direction.

    Args:
        Etot (list): Total energies of all configurations (in eV).
        latoms (list): Sequence of ASE `Atoms` objects representing configurations.

    Returns:
        tuple:
            - dE (np.ndarray): Energy differences relative to the reference configuration.
            - da3 (np.ndarray): Lattice vector changes along the third direction.
            - dpos3 (np.ndarray): Out-of-plane atomic displacements.
    """
    njobs = len(latoms)
    natoms = latoms[0].positions.shape[0]
    print('njobs, natoms:', njobs, natoms)

    dE = np.array([])
    da3 = np.zeros([1, 3])
    dpos3 = np.zeros([1, natoms])
    
    for i in np.arange(njobs):
        dE = np.append(dE, Etot[i]-Etot[0])

   
    # check elem
        if latoms[i].get_chemical_formula() \
            != latoms[0].get_chemical_formula():
            sys.exit('ABORT: wrong chemical formula. ')

        temp = latoms[i].get_atomic_numbers() \
            - latoms[0].get_atomic_numbers()
        vf.confirm_0( temp )

 
        # check latt 
        dlatt = latoms[i].cell[:] - latoms[0].cell[:]
        temp = np.linalg.norm(dlatt[0:2, :])
        if temp > 1e-10:
            print('dlatt:', dlatt)
            print('\n==> i, norm: {0}'.format([i, temp]) )
            sys.exit("==> ABORT: in-plane lattices relaxed. \n" )
    
        temp = dlatt[2,:].copy()
        da3 = np.vstack([ da3, temp[np.newaxis,:] ])
        

        # check pos
        dpos = latoms[i].positions - latoms[0].positions
        dposD = dpos @ np.linalg.inv(latoms[i].cell[:])
        dposD = dposD - np.around(dposD)  
        dpos = dposD @ latoms[i].cell[:]

        temp = np.linalg.norm(dpos[:,0:2])
        if temp > 1e-10:
            print('dpos', dpos)
            print('\n==> i, norm: {0}'.format([i, temp]) )
            #print(dpos)
            sys.exit("==> ABORT: atoms show in-plane relaxation. \n" )
    
        temp = dpos[:, 2].copy()
        temp = temp - temp.mean()
        dpos3 = np.vstack([ dpos3, temp[np.newaxis, :] ])
        
    da3 = np.delete(da3, 0, 0)
    dpos3 = np.delete(dpos3, 0, 0)
    
    if (dE.shape[0] != njobs)  \
        or (da3.shape[0] != njobs) \
        or (da3.shape[1] != 3) \
        or (dpos3.shape[0] != njobs) \
        or (dpos3.shape[1] != natoms):
        sys.exit("==> ABORT: wrong dimensions. \n" )

    for i in np.arange(njobs):
        temp = np.abs(da3[i, 1]*da3[1, 0] - da3[1, 1]*da3[i, 0])
        if temp > 1e-10:
            print('\n==> i, norm: {0}'.format([i, temp]) )
            sys.exit("==> ABORT: slip is not along a line. \n" )
    
    return dE, da3, dpos3

def find_sf_usf(gamma: np.ndarray = None) -> tuple:
    """
    Identify local minima and maxima in GSFE data.

    Local minima correspond to stable stacking faults (SF),
    and local maxima correspond to unstable stacking faults (USF).

    Args:
        gamma (np.ndarray): GSFE values (in mJ/m²).

    Returns:
        tuple:
            - sf (np.ndarray): Local minima (stable faults).
            - usf (np.ndarray): Local maxima (unstable faults).
    """
    njobs = gamma.shape[0]
    print(njobs)
    sf = np.array([])
    usf = np.array([])
    for i in np.arange(1, njobs-1, 1):
        if (gamma[i] < gamma[i-1]) and (gamma[i] < gamma[i+1]):
            sf = np.append(sf, gamma[i])
        if (gamma[i] > gamma[i-1]) and (gamma[i] > gamma[i+1]):
            usf = np.append(usf, gamma[i])
    return sf, usf

def write_output(Asf, a11, a22, E0bulk, sf, usf, jobn, dE, gamma, da3, save_txt_path = './y_post_gsfe.txt',):
    """
    Write GSFE results and derived quantities to a formatted text file.

    Includes surface area, bulk energy, stacking fault energies, and
    displacement-related quantities for each sliding configuration.

    Args:
        Asf (float): Surface area of the slip plane (Å²).
        a11 (float): Lattice constant along a1 direction (Å).
        a22 (float): Lattice constant along a2 direction (Å).
        E0bulk (float): Per-atom bulk energy (eV).
        sf (np.ndarray): Local minima of GSFE (stable faults).
        usf (np.ndarray): Local maxima of GSFE (unstable faults).
        jobn (list): Job or displacement indices.
        dE (np.ndarray): Energy differences (eV).
        gamma (np.ndarray): GSFE values (mJ/m²).
        da3 (np.ndarray): Lattice changes along slip direction.
        save_txt_path (str, optional): Output file path. Defaults to './y_post_gsfe.txt'.

    Returns:
        None
    """
    njobs = gamma.shape[0]
    print(njobs)
       
    f = open(save_txt_path,'w+')
    f.write('# VASP GSFE: \n' )
    f.write('# gamma = dE/Asf \n' )


    f.write('\n%16s %16s %16s %16s \n' \
        %('Asf (Ang^2)', 'a11 (Ang)', 'a22 (Ang)', 'E0_bulk (eV)' ) )
    f.write('%16.8f %16.8f %16.8f %16.8f \n\n' \
        %(Asf, a11, a22, E0bulk ))


    if sf.shape[0] > 0.5 :
        f.write('%20s: %16.8f \n' %('local min (mJ/m^2)', sf.min() ) )
    
    if usf.shape[0] > 0.5:
        f.write('%20s: %16.8f \n' %('local max (mJ/m^2)', usf.min() ) )
        
        
    f.write('\n%10s %10s %16s %10s %10s %10s %10s \n' \
        %('jobn', 'dE (eV)', 'gamma (mJ/m^2)', 
        'da31/a11', 'da32/a22', 'slip (Ang)',
        'da33 (Ang)'  
        ))
    
    for i in np.arange(njobs):
        f.write('%10s %10.4f %16.8f %10.4f %10.4f %10.4f %10.4f \n' \
            %(jobn[i], dE[i], gamma[i], 
            da3[i, 0]/a11,  da3[i, 1]/a22, np.linalg.norm(da3[i, 0:2]),
            da3[i, 2] 
            ))

    f.write(' \n')
    f.close() 
    print(f"✅ gsfe written to '{save_txt_path}'\n")


def read_output(save_txt_path: Union[str, Path] = "./y_post_gsfe.txt",
                reconstruct_da3: bool = False) -> Dict[str, Any]:
    """Read GSFE results written by `write_output()`.

    This function parses the formatted text file generated by
    `write_output` and returns all scalar values and table data
    in a structured dictionary.

    It can optionally reconstruct the original `da3` array using
    the normalized displacement values and lattice constants.

    Args:
        save_txt_path (Union[str, Path]):
            Path to the GSFE output text file.
        reconstruct_da3 (bool, optional):
            If True, reconstruct the full `da3` array with shape (njobs, 3):
                - da3[:, 0] = (da31/a11) * a11
                - da3[:, 1] = (da32/a22) * a22
                - da3[:, 2] = da33
            Defaults to False.

    Returns:
        Dict[str, Any]: A dictionary containing:

            Scalars:
                - Asf (float): Slip plane surface area (Å²).
                - a11 (float): Lattice constant along a1 (Å).
                - a22 (float): Lattice constant along a2 (Å).
                - E0bulk (float): Per-atom bulk energy (eV).
                - sf_min (Optional[float]): Local minimum GSFE (mJ/m²).
                - usf_max (Optional[float]): Local maximum GSFE (mJ/m²).

            Arrays:
                - jobn (np.ndarray): Job identifiers.
                - dE (np.ndarray): Energy differences (eV).
                - gamma (np.ndarray): GSFE values (mJ/m²).
                - da31_over_a11 (np.ndarray): Normalized displacement along a1.
                - da32_over_a22 (np.ndarray): Normalized displacement along a2.
                - slip (np.ndarray): In-plane slip magnitude (Å).
                - da33 (np.ndarray): Out-of-plane displacement (Å).

            Optional:
                - da3 (np.ndarray): Reconstructed displacement array
                  with shape (njobs, 3), returned only if
                  `reconstruct_da3=True`.

    Raises:
        FileNotFoundError: If the specified file does not exist.
        ValueError: If required data blocks cannot be found
            or the file format is malformed.
    """
    p = Path(save_txt_path)
    if not p.exists():
        raise FileNotFoundError(f"File not found: {p}")

    text = p.read_text(encoding="utf-8", errors="ignore")
    lines = [ln.rstrip("\n") for ln in text.splitlines()]

    # 1) 读 Asf/a11/a22/E0bulk：它们在一个标题行后，紧跟一行 4 个浮点数
    Asf = a11 = a22 = E0bulk = None
    for i, ln in enumerate(lines):
        if "Asf (Ang^2)" in ln and "E0_bulk" in ln:
            # 下一行应该是数值
            if i + 1 >= len(lines):
                raise ValueError("Malformed file: missing numeric line after Asf/a11/a22/E0bulk header.")
            nums = lines[i + 1].split()
            if len(nums) < 4:
                raise ValueError(f"Malformed numeric line for Asf/a11/a22/E0bulk: {lines[i+1]!r}")
            Asf, a11, a22, E0bulk = map(float, nums[:4])
            break
    if Asf is None:
        raise ValueError("Could not find Asf/a11/a22/E0bulk block in file.")

    # 2) 读 local min / local max（可能不存在）
    sf_min: Optional[float] = None
    usf_max: Optional[float] = None

    # 你的 write_output 写的是：
    #   'local min (mJ/m^2): %16.8f'
    #   'local max (mJ/m^2): %16.8f'
    # 注意：你写 usf 的时候用的是 usf.min()（可能是 bug），但读文件只按文字解析，不做纠正
    for ln in lines:
        m = re.search(r"local min\s*\(mJ/m\^2\)\s*:\s*([-\d\.Ee+]+)", ln)
        if m:
            sf_min = float(m.group(1))
        m = re.search(r"local max\s*\(mJ/m\^2\)\s*:\s*([-\d\.Ee+]+)", ln)
        if m:
            usf_max = float(m.group(1))

    # 3) 定位表头行，然后读数据行直到遇到空行/非数据
    header_idx = None
    for i, ln in enumerate(lines):
        if ln.strip().startswith("jobn") and "dE" in ln and "gamma" in ln and "da33" in ln:
            header_idx = i
            break
    if header_idx is None:
        # 你的文件里表头是用格式化写的，前面可能有空格：
        for i, ln in enumerate(lines):
            if "jobn" in ln and "dE" in ln and "gamma" in ln and "da33" in ln:
                header_idx = i
                break
    if header_idx is None:
        raise ValueError("Could not find table header line (jobn, dE, gamma, ...) in file.")

    data_rows: List[List[str]] = []
    for ln in lines[header_idx + 1:]:
        if not ln.strip():
            # 遇到空行就结束
            break
        parts = ln.split()
        # 期望 7 列：jobn dE gamma da31/a11 da32/a22 slip da33
        if len(parts) < 7:
            # 如果出现尾部其它文字（例如 "✅ gsfe written to ..."）也会到这里，直接停止
            break
        data_rows.append(parts[:7])

    if not data_rows:
        raise ValueError("No data rows found under the table header.")

    # 4) 转成数组
    jobn = np.array([row[0] for row in data_rows], dtype=object)
    dE = np.array([float(row[1]) for row in data_rows], dtype=float)
    gamma = np.array([float(row[2]) for row in data_rows], dtype=float)
    da31_over_a11 = np.array([float(row[3]) for row in data_rows], dtype=float)
    da32_over_a22 = np.array([float(row[4]) for row in data_rows], dtype=float)
    slip = np.array([float(row[5]) for row in data_rows], dtype=float)
    da33 = np.array([float(row[6]) for row in data_rows], dtype=float)

    out: Dict[str, Any] = dict(
        Asf=Asf, a11=a11, a22=a22, E0bulk=E0bulk,
        sf_min=sf_min, usf_max=usf_max,
        jobn=jobn,
        dE=dE, gamma=gamma,
        da31_over_a11=da31_over_a11,
        da32_over_a22=da32_over_a22,
        slip=slip,
        da33=da33,
    )

    if reconstruct_da3:
        da3 = np.zeros((len(jobn), 3), dtype=float)
        da3[:, 0] = da31_over_a11 * a11
        da3[:, 1] = da32_over_a22 * a22
        da3[:, 2] = da33
        out["da3"] = da3

    return out



def plot_GSFE(jobn, gamma, da3, dpos3, latoms, str_all, save_fig_path = './y_post_gsfe.pdf', save_u3_fig_path = './y_post_gsfe.u3.pdf',):
    """
    Plot GSFE energy curve, displacement, and shear stress evolution.

    Generates two plots:
      1. GSFE vs. normalized slip vector (with stress and normal displacement).
      2. Atomic out-of-plane displacement (u3) profiles for all configurations.

    Args:
        jobn (list): Normalized displacement steps or job indices.
        gamma (np.ndarray): GSFE values (mJ/m²).
        da3 (np.ndarray): Lattice vector changes along slip direction.
        dpos3 (np.ndarray): Out-of-plane atomic displacements.
        latoms (list): Sequence of ASE `Atoms` objects.
        str_all (str): Summary label (chemical formula, area info).
        save_fig_path (str, optional): Output file for GSFE plot. Defaults to './y_post_gsfe.pdf'.
        save_u3_fig_path (str, optional): Output file for u3 plot. Defaults to './y_post_gsfe.u3.pdf'.

    Returns:
        None
    """
    njobs = gamma.shape[0]
    print(njobs)

    fig_subp = [3, 1]
    lg = general_set_all_rcParams(figure_subp=fig_subp, legend_framealpha=0.4,
                                  font_family=['Arial'])
    fig, ax1 = plt.subplots(fig_subp[0], fig_subp[1], sharex = True)

    xi = np.array([])
    disp = np.array([])
    for i in np.arange( njobs ):
        xi = np.append(xi, float(jobn[i]) )
        disp = np.append(disp, np.linalg.norm(da3[i, 0:2]))

    xi = xi / np.around( np.max([xi.max(), 10]) , -1)

    ax1[0].plot(xi, gamma, '-o')   
    ax1[1].plot(xi, da3[:,2], '-o')
    
    tau = np.diff(gamma) / np.diff(disp) *1e-2  #[GPa]
    x_tau = xi[0:-1].copy() + np.diff(xi)/2
    ax1[2].plot(x_tau, tau, '-o')
    ax1[2].plot([xi.min(), xi.max()], [0, 0], '--k')


    ax1[-1].set_xlabel('Normalized slip vector')
    ax1[0].set_ylabel('GSFE (mJ/m$^2$)')
    ax1[1].set_ylabel('Inelastic normal displacement ($\\mathrm{\\AA}$)')
    ax1[2].set_ylabel('Shear stress $\\tau$ (GPa)')

    dxi = np.around( xi.max()/6, 1)
    ax1[-1].set_xticks( np.arange(0, xi.max()+dxi, dxi ) )

    ax1[2].text(0, tau.min()/2, \
        '$\\tau_\\mathrm{max} =$ %.1f GPa' %( tau.max() ))

    ax1[0].text( 0.3, gamma.max()*0.2, str_all )


    plt.savefig(save_fig_path)


    #=====================
    fig_subp = [1, 1]
    lg = general_set_all_rcParams(figure_subp=fig_subp, legend_framealpha=0.4,
                                  font_family=['Arial'])
    fig, ax2 = plt.subplots(fig_subp[0], fig_subp[1], sharex = True)


    xi = latoms[0].positions[:, 2]
    for i in np.arange(njobs):
        temp = np.array([ xi, dpos3[i, :] ])
        ind = np.argsort(temp[0, :])
        temp2 = temp[:,ind]

        ax2.plot(temp2[0, :], temp2[1, :], '-o', label=f'{float(jobn[i]):.2f}')
    
    ax2.legend(loc='lower center', ncol=5,fontsize = 10, bbox_to_anchor=(0.5, 0.0))
    ax2.set_xlabel('Atom positions in $x_3$ ($\\mathrm{\\AA}$)')
    ax2.set_ylabel('Displacement $u_3$ ($\\mathrm{\\AA}$)')

    plt.savefig(save_u3_fig_path)
