"""
hoec_energy post-processing submodule.

Post-process the deformed VASP jobs generated by
:func:`mymetal.build.workflow.hoec.generate_hoec_dirs` and solve for the 2nd/3rd/4th-order
elastic constants.

For each single-parameter mode the strain-energy density::

    u(xi) = [U(xi) - U(0)] / V0   [GPa]

is fitted to a polynomial; the xi^2, xi^3, xi^4 coefficients give P2, P3, P4. Across all
modes these are stacked into the linear systems::

    A2 @ SOEC = P2,   A3 @ TOEC = P3,   A4 @ FOEC = P4

whose coefficient matrices come from :mod:`mymetal.calculate.calmechanics.hoec` (exactly
the Wang-Li Table I system for cubic, and its hexagonal generalization). The systems are
overdetermined -- e.g. hex FOEC solves 19 constants from 19+ modes -- and are solved by
least squares.

Energies are read the same way as every other VASP workflow in this package
(``mymetal.post.stretch``, ``mymetal.post.Cij_energy``): ``pei_vasp_univ_post`` scrapes the
OUTCARs into ``y_post_data.txt``, then ``myvasp.vasp_func.vasp_read_post_data`` reads it.
``Etot`` from that file is ``energy(sigma->0)``. It is run once at the top of
``y_hoec_energy``; it descends into every ``y_dir`` and writes ``y_post_data.txt`` (plus
``y_post_time.txt`` / ``y_post_warning.txt``, which ``pei_vasp_plot_all`` summarizes) next
to each one, i.e. one per mode directory, exactly where the Cij workflow puts it.

Outputs (written into ``y_hoec_energy/``):
    - ``y_post_hoec.txt``   human-readable constants + per-mode fit diagnostics
    - ``y_post_hoec.json``  machine-readable constants
    - ``y_post_hoec.pdf``   per-mode energy-strain curves with fits

Functions:
    - post_hoec_energy: Main entry; read energies, fit, solve, report and plot.
    - run_univ_post: Run pei_vasp_univ_post over the whole y_hoec_energy tree.
    - load_hoec_manifest: Load ``y_hoec_modes.json``.
    - read_element: Read the chemical element from a deformed POSCAR.
    - collect_mode_data: Per-mode (xi, u) arrays within the fit window.
    - fit_P: Polynomial fit of u(xi) -> P0..P4 and the rms residual.
    - solve_constants: Least-squares solve for SOEC/TOEC/FOEC.
    - load_ref_constants: Literature constants for the cubic sanity check.
    - write_hoec_energy: Write the txt report and the json constants.
    - read_hoec_energy: Read back the json constants.
    - plot_hoec_energy: Per-mode energy-strain curves with fits.

Change log:
    - Written by J. P., 2026, as the standalone ``pei_vasp_post_hoec_energy.py`` script.
    - Merged into mymetal by J. P. on 2026-07-10; kept as the higher-order sibling of
      ``mymetal.post.Cij_energy``.
    - Revised by J. P. on 2026-07-10 to read energies through ``pei_vasp_univ_post`` +
      ``vf.vasp_read_post_data`` and to plot through ``general_set_all_rcParams``, so the
      workflow matches ``mymetal.post.stretch`` and ``mymetal.post.Cij_energy``.
"""

import json
import os
import shutil
import numpy as np
from pathlib import Path
from ase.io import read
import matplotlib.pyplot as plt
from myvasp import vasp_func as vf

from mymetal.calculate.calmechanics.hoec import MODES, get_model
from mymetal.post.general import my_ployfit
from mymetal.universal.plot.general import general_set_all_rcParams
from mymetal.universal.print.print import fail, warn

# literature FCC constants (Wang-Li 2009), for a sanity comparison of the cubic run
REF_JSON_DEFAULT = Path("/public3/home/scg6928/mywork/20260227_cu_ag_al/"
                        "ai-guide/elastic_constants.txt")

ORDER_KEY = {2: 'second_order', 3: 'third_order', 4: 'fourth_order'}

UNIV_POST = "pei_vasp_univ_post"


# ---------------------------------------------------------------------------
# readers
# ---------------------------------------------------------------------------
def run_univ_post(path_out: Path = None) -> None:
    """Run ``pei_vasp_univ_post`` over the whole tree to build the ``y_post_data.txt`` files.

    Mirrors ``mymetal.post.stretch.post_stretch``. It finds every ``y_dir`` below
    ``path_out`` and writes one ``y_post_data.txt`` beside each, i.e. one per mode.

    stdin is fed from /dev/null so the run stays non-interactive: HOEC always has 11 (cubic)
    or 19 (hex) ``y_dir``, which trips ``pei_vasp_univ_post``'s "too many dir, continue?"
    confirmation whenever that guard is enabled.

    Args:
        path_out (Path): The ``y_hoec_energy`` directory.

    Returns:
        None
    """
    path_back = Path.cwd()
    os.chdir(path_out)
    try:
        os.system(UNIV_POST + " < /dev/null")
    finally:
        os.chdir(path_back)      # every caller continues from a known cwd


def load_hoec_manifest(path_out: Path = None) -> dict:
    """Load the ``y_hoec_modes.json`` manifest written by the generator.

    Args:
        path_out (Path): The ``y_hoec_energy`` directory.

    Returns:
        dict: The manifest.
    """
    path_man = Path(path_out) / "y_hoec_modes.json"
    if not path_man.is_file():
        fail("manifest not found: %s (run pei_vasp_run_hoec_energy first)" % path_man)
    return json.loads(path_man.read_text(encoding='utf-8'))


def read_element(path_out: Path = None, dict_manifest: dict = None) -> str:
    """Read the chemical element from a deformed POSCAR (for the literature check).

    Args:
        path_out (Path): The ``y_hoec_energy`` directory.
        dict_manifest (dict): The manifest.

    Returns:
        str: The element symbol, or None when no POSCAR can be read.
    """
    for name, info in dict_manifest["modes"].items():
        p = (Path(path_out) / ("y_hoec_energy_" + name) / "y_dir"
             / info["strain_dirs"][0] / "POSCAR")
        if p.is_file():
            return read(p, format='vasp').get_chemical_symbols()[0]
    return None


def collect_mode_data(path_out: Path = None, dict_manifest: dict = None,
                      fitmax: float = None, run_post: bool = True) -> tuple:
    """Read the energies per mode and convert them to strain-energy densities.

    Args:
        path_out (Path): The ``y_hoec_energy`` directory.
        dict_manifest (dict): The manifest.
        fitmax (float): Only keep points with |xi| <= fitmax.
        run_post (bool): Re-run ``pei_vasp_univ_post`` before reading. Set False to
            re-fit an already-scraped tree (e.g. when scanning ``fitmax``).

    Returns:
        tuple: ``(dict_data, lmissing)`` where ``dict_data`` maps mode name to
        ``(xi, u_gpa)`` arrays and ``lmissing`` lists strain points without an energy.
    """
    if run_post:
        if shutil.which(UNIV_POST) is None:
            fail("%s not on PATH; source the vasp_utils environment first" % UNIV_POST)
        run_univ_post(path_out)

    v0 = dict_manifest["v0_ang3"]
    conv = vf.phy_const('qe') * 1e21          # eV/A^3 -> GPa, as in mymetal.post.Cij_energy
    dict_data = {}
    lmissing = []
    for name, info in dict_manifest["modes"].items():
        path_mode = Path(path_out) / ("y_hoec_energy_" + name)
        path_data = path_mode / "y_post_data.txt"
        if not path_data.is_file():
            warn("mode %s: no y_post_data.txt; skipped" % name)
            continue

        # jobn are the y_dir subdirectory names, i.e. the strain labels 's_+0.0100'
        jobn, Etot, Eent, pres = vf.vasp_read_post_data(str(path_data))
        dict_e = {j: e for j, e in zip(jobn, Etot)}
        lmissing += ["%s/%s" % (name, lbl) for lbl in info["strain_dirs"]
                     if lbl not in dict_e]

        u0 = dict_e.get("s_%+.4f" % 0.0)      # this mode's own xi=0 reference
        if u0 is None:
            warn("mode %s: no xi=0 reference energy; skipped" % name)
            continue

        lxi, lu = [], []
        for lbl, e in dict_e.items():
            xi = float(lbl.split("_")[1])
            if abs(xi) <= fitmax + 1e-9:
                lxi.append(xi)
                lu.append((e - u0) * conv / v0)
        dict_data[name] = (np.array(lxi), np.array(lu))
    return dict_data, lmissing


# ---------------------------------------------------------------------------
# fit and solve
# ---------------------------------------------------------------------------
def fit_P(xi: np.ndarray = None, u: np.ndarray = None, fitdeg: int = 6) -> tuple:
    """Fit u(xi) to a polynomial and return its low-order coefficients.

    The fit degree is raised above 4 so that the neglected xi^5, xi^6 terms do not leak
    into P4 (Wang-Li fit the same way).

    Args:
        xi (np.ndarray): Strain amplitudes.
        u (np.ndarray): Strain-energy densities (GPa).
        fitdeg (int): Polynomial degree; clipped to len(xi)-1 when there are few points.

    Returns:
        tuple: ``(P0, P1, P2, P3, P4, rms)``.
    """
    if len(xi) < fitdeg + 1:
        fitdeg = len(xi) - 1
    coeffs, u_fit = my_ployfit(xi, u, fitdeg)       # coeffs: highest power first
    lp = coeffs[::-1]                               # now index = power
    P = [lp[k] if k < len(lp) else 0.0 for k in range(5)]
    rms = float(np.sqrt(np.mean((u_fit - u) ** 2)))
    return P[0], P[1], P[2], P[3], P[4], rms


def solve_constants(model=None, dict_P: dict = None) -> dict:
    """Least-squares solve for SOEC/TOEC/FOEC from the per-mode P coefficients.

    Args:
        model (HOECModel): The reduced model for this symmetry.
        dict_P (dict): Mode name -> dict with keys ``P2``, ``P3``, ``P4``.

    Returns:
        dict: Order -> dict with ``names``, ``values``, ``rank``, ``nconst``, ``resid``.
    """
    lname = list(dict_P.keys())
    lmode = [MODES[model.symmetry][n] for n in lname]
    dict_result = {}
    for order, key in ((2, 'P2'), (3, 'P3'), (4, 'P4')):
        A = model.system(order, lmode)
        b = np.array([dict_P[n][key] for n in lname])
        sol, res, rank, sv = np.linalg.lstsq(A, b, rcond=None)
        pred = A @ sol
        if rank < A.shape[1]:
            warn("order %d: rank %d < %d constants — some are undetermined; "
                 "the remaining modes do not span the system"
                 % (order, rank, A.shape[1]))
        dict_result[order] = dict(names=model.names(order), values=sol,
                                  rank=int(rank), nconst=A.shape[1],
                                  resid=float(np.sqrt(np.mean((pred - b) ** 2))))
    return dict_result


def load_ref_constants(element: str = None, path_ref: str = None) -> dict:
    """Literature constants for one element, used only for the cubic sanity check.

    Args:
        element (str): Element symbol.
        path_ref (str): Path to the literature json.

    Returns:
        dict: The element's block, or None when unavailable.
    """
    if element is None or path_ref is None or not Path(path_ref).is_file():
        return None
    dict_data = json.loads(Path(path_ref).read_text(encoding='utf-8'))
    return dict_data.get(element.capitalize())


# ---------------------------------------------------------------------------
# report and plot
# ---------------------------------------------------------------------------
def write_hoec_energy(path_out: Path = None, dict_manifest: dict = None,
                      dict_P: dict = None, dict_result: dict = None,
                      element: str = None, dict_ref: dict = None,
                      fitdeg: int = 6, fitmax: float = None,
                      save_txt_path: str = None, save_json_path: str = None) -> None:
    """Write ``y_post_hoec.txt`` (report) and ``y_post_hoec.json`` (constants).

    Args:
        path_out (Path): The ``y_hoec_energy`` directory.
        dict_manifest (dict): The manifest.
        dict_P (dict): Per-mode fit coefficients.
        dict_result (dict): Output of :func:`solve_constants`.
        element (str): Element symbol.
        dict_ref (dict): Literature constants, or None.
        fitdeg (int): Polynomial degree used.
        fitmax (float): Fit window used.
        save_txt_path (str): Output txt; defaults to ``path_out/y_post_hoec.txt``.
        save_json_path (str): Output json; defaults to ``path_out/y_post_hoec.json``.

    Returns:
        None
    """
    path_out = Path(path_out)
    path_txt = Path(save_txt_path) if save_txt_path else path_out / "y_post_hoec.txt"
    path_json = Path(save_json_path) if save_json_path else path_out / "y_post_hoec.json"

    lline = []
    lline.append("higher-order elastic constants (GPa)")
    lline.append("symmetry=%s  element=%s  V0=%.4f A^3  natoms=%d"
                 % (dict_manifest["symmetry"], element,
                    dict_manifest["v0_ang3"], dict_manifest["natoms"]))
    lline.append("fit: polynomial degree %d over |xi|<=%.4f" % (fitdeg, fitmax))
    lline.append("=" * 64)
    for order in (2, 3, 4):
        r = dict_result[order]
        lline.append("\n--- order %d : %d constants (system rank %d) resid=%.3f GPa"
                     % (order, r['nconst'], r['rank'], r['resid']))
        dict_refblk = dict_ref.get(ORDER_KEY[order]) if dict_ref else None
        head = "  %-8s %12s" % ("const", "this work")
        if dict_refblk:
            head += " %12s %10s" % ("Wang-Li", "diff")
        lline.append(head)
        for nm, val in zip(r['names'], r['values']):
            row = "  C%-7s %12.2f" % (nm, val)
            if dict_refblk and ("C" + nm) in dict_refblk:
                rv = dict_refblk["C" + nm]
                row += " %12.2f %10.2f" % (rv, val - rv)
            lline.append(row)
    lline.append("\n--- per-mode fit (P1 should be ~0 at the relaxed reference)")
    lline.append("  %-5s %10s %10s %10s %10s %8s" % ("mode", "P1", "P2", "P3", "P4", "rms"))
    for n in dict_P:
        p = dict_P[n]
        lline.append("  %-5s %10.2f %10.1f %10.1f %10.1f %8.3f"
                     % (n, p['P1'], p['P2'], p['P3'], p['P4'], p['rms']))
    text = "\n".join(lline) + "\n"
    path_txt.write_text(text, encoding='utf-8')
    print(text)

    dict_out = dict(symmetry=dict_manifest["symmetry"], element=element,
                    v0_ang3=dict_manifest["v0_ang3"], fitdeg=fitdeg, fitmax=fitmax,
                    constants={ORDER_KEY[o]: {("C" + nm): float(v)
                               for nm, v in zip(dict_result[o]['names'],
                                                dict_result[o]['values'])}
                               for o in (2, 3, 4)})
    path_json.write_text(json.dumps(dict_out, indent=2), encoding='utf-8')
    print("✅ HOEC written to '%s' and '%s'" % (path_txt, path_json))


def read_hoec_energy(save_json_path: str = './y_post_hoec.json') -> dict:
    """Read elastic constants written by :func:`write_hoec_energy`.

    Mirrors :func:`mymetal.post.Cij_energy.read_cij_energy`, but reads the machine-readable
    json rather than the formatted report.

    Args:
        save_json_path (str): Path to the file written by ``write_hoec_energy``.

    Returns:
        dict: Keys ``symmetry``, ``element``, ``v0_ang3``, ``fitdeg``, ``fitmax`` and
        ``constants`` (with ``second_order`` / ``third_order`` / ``fourth_order`` blocks
        mapping e.g. ``C1111`` -> GPa).

    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If the constants block cannot be located.
    """
    p = Path(save_json_path)
    if not p.is_file():
        raise FileNotFoundError(f"File not found: {p}")
    dict_out = json.loads(p.read_text(encoding='utf-8'))
    if 'constants' not in dict_out:
        raise ValueError(f"Could not find the 'constants' block in {p}.")
    return dict_out


def plot_hoec_energy(path_out: Path = None, dict_data: dict = None,
                     dict_P: dict = None, save_fig_path: str = None) -> None:
    """Plot the per-mode energy-strain curves with their fits.

    Args:
        path_out (Path): The ``y_hoec_energy`` directory.
        dict_data (dict): Mode name -> (xi, u) arrays.
        dict_P (dict): Per-mode fit coefficients.
        save_fig_path (str): Output pdf; defaults to ``path_out/y_post_hoec.pdf``.

    Returns:
        None
    """
    path_fig = Path(save_fig_path) if save_fig_path else Path(path_out) / "y_post_hoec.pdf"
    lname = list(dict_data.keys())
    ncol = 4
    nrow = int(np.ceil(len(lname) / ncol))

    fig_subp = [nrow, ncol]
    general_set_all_rcParams(figure_subp=fig_subp, legend_framealpha=0.4,
                             font_family=['Arial'])
    fig, axes = plt.subplots(fig_subp[0], fig_subp[1], sharex=True)
    axes = np.array(axes).reshape(-1)

    for ax, n in zip(axes, lname):
        xi, u = dict_data[n]
        idx = np.argsort(xi)
        ax.plot(xi[idx], u[idx], 'o')
        xs = np.linspace(xi.min(), xi.max(), 200)
        p = dict_P[n]
        ys = p['P1'] * xs + p['P2'] * xs**2 + p['P3'] * xs**3 + p['P4'] * xs**4
        ax.plot(xs, ys, '-C1')
        ax.set_title(n)
    for ax in axes[len(lname):]:
        ax.axis('off')

    for i in range(ncol):
        axes[(nrow - 1) * ncol + i].set_xlabel('Strain $\\xi$')
    for i in range(nrow):
        axes[i * ncol].set_ylabel('Elastic energy density (GPa)')

    plt.savefig(path_fig)
    plt.close(fig)                     # free the figure: 19 hex modes per phase adds up
    print("📈 wrote %s" % path_fig)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def post_hoec_energy(dir: str = 'y_hoec_energy', fitdeg: int = 6,
                     fitmax: float = None, refjson: str = None,
                     run_post: bool = True) -> dict:
    """Solve the higher-order elastic constants from a finished ``y_hoec_energy`` tree.

    Args:
        dir (str): The ``y_hoec_energy`` directory.
        fitdeg (int): Polynomial fit degree (>=4).
        fitmax (float): Max |xi| used in the fit; defaults to the manifest's ``emax``.
            Scan it (0.08-0.15) to check the 4th-order plateau (Wang-Li Fig. 6).
        refjson (str): Literature json for the cubic sanity check; defaults to
            :data:`REF_JSON_DEFAULT`.
        run_post (bool): Re-run ``pei_vasp_univ_post`` before reading the energies.

    Returns:
        dict: Output of :func:`solve_constants`, keyed by order.
    """
    ### check ------------------------------------------------------------------
    path_out = Path(dir).resolve()
    if not path_out.is_dir():
        fail("directory not found: %s" % path_out)
    if fitdeg < 4:
        fail("fitdeg must be >= 4 to resolve P4, got %d" % fitdeg)
    dict_manifest = load_hoec_manifest(path_out)
    fitmax = fitmax if fitmax is not None else dict_manifest["emax"]
    model = get_model(dict_manifest["symmetry"])

    ### prepare: scrape the OUTCARs, read energies, fit each mode ---------------
    print("🟢 post-processing %s (symmetry=%s)" % (path_out, dict_manifest["symmetry"]))
    dict_data, lmissing = collect_mode_data(path_out, dict_manifest, fitmax, run_post)
    if lmissing:
        warn("%d strain points missing energy (unconverged/not run):" % len(lmissing))
        print("    " + ", ".join(lmissing[:12]) + (" ..." if len(lmissing) > 12 else ""))
    if not dict_data:
        fail("no usable energies found — are the jobs finished?")

    dict_P = {}
    for n, (xi, u) in dict_data.items():
        P0, P1, P2, P3, P4, rms = fit_P(xi, u, fitdeg)
        dict_P[n] = dict(P0=P0, P1=P1, P2=P2, P3=P3, P4=P4, rms=rms)

    ### main: solve, report, plot ----------------------------------------------
    dict_result = solve_constants(model, dict_P)
    element = read_element(path_out, dict_manifest)
    dict_ref = None
    if dict_manifest["symmetry"] == "cubic":
        dict_ref = load_ref_constants(element, refjson or str(REF_JSON_DEFAULT))

    write_hoec_energy(path_out, dict_manifest, dict_P, dict_result, element, dict_ref,
                      fitdeg, fitmax)
    plot_hoec_energy(path_out, dict_data, dict_P)

    print("📊 SUMMARY: %s | %d/%d modes used | %d strain points missing"
          % (dict_manifest["symmetry"], len(dict_data),
             len(dict_manifest["modes"]), len(lmissing)))
    print("🎉 done")
    return dict_result
