"""Post-process and plot VASP KPAR/NCORE timing benchmarks.

``pei_vasp_univ_post`` first extracts one ``Elapsedtime`` value per benchmark
directory into ``y_post_time.txt``.  This module reads those seconds, converts
them to minutes, writes a sortable table, and draws all six KPAR curves in one
NCORE timing panel.

Functions:
    - run_univ_post: Generate the standard ``y_post_*`` files.
    - read_kpar_ncore_times: Parse benchmark labels and elapsed seconds.
    - write_kpar_ncore_times: Write the timing table and fastest combination.
    - plot_kpar_ncore_times: Draw the one-panel KPAR timing figure.
    - post_kpar_ncore: Run the complete post-processing workflow.

The command-line front end lives in ``pei_vasp_plot_kpar_ncore``; this module stays
import-only, exactly like ``mymetal.post.hoec_energy``.
"""

import re
import shutil
import subprocess
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from mymetal.universal.print.print import fail, warn
from mymetal.universal.plot.workflow import my_plot_kpar_ncore


KPAR_ORDER = [128, 64, 32, 16, 8, 4]
EXPECTED_PAIRS = {
    128: [1],
    64: [1, 2],
    32: [1, 2, 4],
    16: [1, 2, 4, 8],
    8: [1, 2, 4, 8, 16],
    4: [1, 2, 4, 8, 16, 32],
}
UNIV_POST = "pei_vasp_univ_post"
CASE_PATTERN = re.compile(r"^kpar_(\d+)_ncore_(\d+)$")
TIME_PATTERN = re.compile(
    r"^(\S+).*?Elapsedtime\s+([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?)")


def run_univ_post(path_workflow: Path) -> None:
    """Run ``pei_vasp_univ_post`` in the benchmark workflow directory.

    Args:
        path_workflow (Path): Directory containing ``y_dir``.
    """
    if shutil.which(UNIV_POST) is None:
        fail("%s not on PATH; source the vasp_utils environment first" % UNIV_POST)
    print("▶️  running %s in %s" % (UNIV_POST, path_workflow))
    subprocess.run([UNIV_POST], cwd=path_workflow, check=True)


def read_kpar_ncore_times(path_time: Path) -> dict[tuple[int, int], float]:
    """Read elapsed seconds from a standard ``y_post_time.txt``.

    Args:
        path_time (Path): File generated by ``pei_vasp_univ_post``.

    Returns:
        dict[tuple[int, int], float]: ``(KPAR, NCORE) -> elapsed seconds``.
    """
    if not path_time.is_file():
        fail("post-time file not found: %s" % path_time)

    dict_seconds = {}
    lunknown = []
    for line in path_time.read_text(encoding="utf-8").splitlines():
        match_time = TIME_PATTERN.search(line)
        if match_time is None:
            continue
        label = match_time.group(1)
        match_case = CASE_PATTERN.fullmatch(label)
        if match_case is None:
            lunknown.append(label)
            continue
        pair = (int(match_case.group(1)), int(match_case.group(2)))
        if pair in dict_seconds:
            fail("duplicate timing row for KPAR=%d, NCORE=%d in %s"
                 % (pair[0], pair[1], path_time))
        dict_seconds[pair] = float(match_time.group(2))

    if lunknown:
        warn("ignored timing rows with unrecognized labels: %s"
             % ", ".join(sorted(set(lunknown))))
    if not dict_seconds:
        fail("no completed kpar_<KPAR>_ncore_<NCORE> timing rows found in %s"
             % path_time)
    return dict_seconds


def get_missing_pairs(dict_seconds: dict[tuple[int, int], float]) -> list[tuple[int, int]]:
    """Return default benchmark pairs that have no elapsed time yet."""
    lmissing = []
    for kpar in KPAR_ORDER:
        for ncore in EXPECTED_PAIRS[kpar]:
            if (kpar, ncore) not in dict_seconds:
                lmissing.append((kpar, ncore))
    return lmissing


def write_kpar_ncore_times(dict_seconds: dict[tuple[int, int], float],
                           path_save: Path) -> None:
    """Write timing data and the measured fastest combination.

    Args:
        dict_seconds (dict[tuple[int, int], float]): Parsed elapsed seconds.
        path_save (Path): Output text path.
    """
    best_pair = min(dict_seconds, key=dict_seconds.get)
    lline = [
        "# KPAR/NCORE VASP elapsed-time benchmark",
        "# best: KPAR=%d NCORE=%d time_min=%.6f"
        % (best_pair[0], best_pair[1], dict_seconds[best_pair] / 60.0),
        "# KPAR NCORE elapsed_seconds time_min",
    ]
    for kpar in KPAR_ORDER:
        lpairs = sorted(
            [pair for pair in dict_seconds if pair[0] == kpar],
            key=lambda pair: pair[1],
        )
        for pair in lpairs:
            seconds = dict_seconds[pair]
            lline.append("%6d %6d %15.6f %12.6f"
                         % (pair[0], pair[1], seconds, seconds / 60.0))
    path_save.write_text("\n".join(lline) + "\n", encoding="utf-8")


def plot_kpar_ncore_times(dict_seconds: dict[tuple[int, int], float],
                          path_save: Path) -> None:
    """Send prepared timing values to the standard workflow plotter.

    Args:
        dict_seconds (dict[tuple[int, int], float]): Parsed elapsed seconds.
        path_save (Path): Figure path, normally PDF or PNG.
    """
    dict_minutes = {
        pair: seconds / 60.0 for pair, seconds in dict_seconds.items()
    }
    lxtick = sorted({ncore for lncore in EXPECTED_PAIRS.values()
                     for ncore in lncore})
    fig, _ = my_plot_kpar_ncore(
        dict_time=dict_minutes,
        lkpar=KPAR_ORDER,
        lncore=lxtick,
        if_save=True,
        savefile=path_save,
    )
    plt.close(fig)


def post_kpar_ncore(path_workflow: str = None, run_post: bool = True,
                     save_fig_path: str = None,
                     save_txt_path: str = None) -> dict[tuple[int, int], float]:
    """Run standard post-processing and create the timing outputs.

    Args:
        path_workflow (str): Directory containing ``y_dir``.
        run_post (bool): Run ``pei_vasp_univ_post`` before reading times.
        save_fig_path (str): Figure path. Defaults to
            ``p_post_kpar_ncore.pdf`` inside the workflow.
        save_txt_path (str): Table path. Defaults to
            ``p_post_kpar_ncore.txt`` inside the workflow.

    Returns:
        dict[tuple[int, int], float]: Parsed elapsed seconds.
    """
    ### check ------------------------------------------------------------------
    if path_workflow is None:
        fail("path_workflow is required")
    path_workflow = Path(path_workflow).resolve()
    if not path_workflow.is_dir():
        fail("workflow directory not found: %s" % path_workflow)
    if not (path_workflow / "y_dir").is_dir():
        fail("y_dir not found under %s" % path_workflow)
    # to here: the standard workflow layout is available

    ### prepare ----------------------------------------------------------------
    if run_post:
        run_univ_post(path_workflow)
    path_time = path_workflow / "y_post_time.txt"
    dict_seconds = read_kpar_ncore_times(path_time)
    path_fig = (Path(save_fig_path).resolve() if save_fig_path
                else path_workflow / "p_post_kpar_ncore.pdf")
    path_txt = (Path(save_txt_path).resolve() if save_txt_path
                else path_workflow / "p_post_kpar_ncore.txt")
    # to here: elapsed times and output paths are ready

    ### main -------------------------------------------------------------------
    write_kpar_ncore_times(dict_seconds, path_txt)
    plot_kpar_ncore_times(dict_seconds, path_fig)
    lmissing = get_missing_pairs(dict_seconds)
    best_pair = min(dict_seconds, key=dict_seconds.get)
    print("\n================ 📊 Summary")
    print("completed=%d    missing=%d" % (len(dict_seconds), len(lmissing)))
    if lmissing:
        warn("missing elapsed times: %s"
             % ", ".join("(%d,%d)" % pair for pair in lmissing))
    print("✅ best measured: KPAR=%d NCORE=%d time=%.6f min"
          % (best_pair[0], best_pair[1], dict_seconds[best_pair] / 60.0))
    print("📄 table : %s" % path_txt)
    print("📈 figure: %s" % path_fig)
    print("🎉 Done: KPAR/NCORE timing post-processing complete")
    return dict_seconds
