"""Post-process and plot VASP KPAR/NCORE timing and energy benchmarks.

``pei_vasp_univ_post`` first extracts one ``Elapsedtime`` value per benchmark
directory into ``y_post_time.txt`` and ``energy(sigma->0)`` into
``y_post_data.txt``.  This module reads both quantities, writes a sortable
table, and draws timing plus relative-energy panels for all six KPAR values.

Functions:
    - run_univ_post: Generate the standard ``y_post_*`` files.
    - read_kpar_ncore_times: Parse benchmark labels and elapsed seconds.
    - read_kpar_ncore_energies: Parse benchmark labels and total energies.
    - read_vasp_natoms: Read atom counts without requiring chemical symbols.
    - get_kpar_ncore_natoms: Read the benchmark structure's atom count.
    - get_delta_energies: Convert total energies to relative meV/atom.
    - write_kpar_ncore_times: Write timing and energy data plus the fastest pair.
    - post_kpar_ncore: Run the complete post-processing workflow.

The command-line front end lives in ``pei_vasp_plot_kpar_ncore``; this module stays
import-only, exactly like ``mymetal.post.hoec_energy``.
"""

import re
import shutil
import subprocess
from pathlib import Path

from mymetal.universal.print.print import fail, warn
from mymetal.universal.plot.workflow import my_plot_kpar_ncore


KPAR_ORDER = [128, 64, 32, 16, 8, 4]
EXPECTED_PAIRS = {
    128: [1],
    64: [1, 2],
    32: [1, 2, 4],
    16: [1, 2, 4, 8],
    8: [1, 2, 4, 8, 16],
    4: [1, 2, 4, 8, 16, 32],
}
UNIV_POST = "pei_vasp_univ_post"
CASE_PATTERN = re.compile(r"^kpar_(\d+)_ncore_(\d+)$")
FLOAT_PATTERN = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?"
TIME_PATTERN = re.compile(
    r"^(\S+).*?Elapsedtime\s+(" + FLOAT_PATTERN + r")")
ENERGY_PATTERN = re.compile(
    r"^(\S+)\s+(" + FLOAT_PATTERN + r")(?:\s|$)")


def run_univ_post(path_workflow: Path) -> None:
    """Run ``pei_vasp_univ_post`` in the benchmark workflow directory.

    Args:
        path_workflow (Path): Directory containing ``y_dir``.
    """
    if shutil.which(UNIV_POST) is None:
        fail("%s not on PATH; source the vasp_utils environment first" % UNIV_POST)
    print("▶️  running %s in %s" % (UNIV_POST, path_workflow))
    subprocess.run([UNIV_POST], cwd=path_workflow, check=True)


def read_kpar_ncore_times(path_time: Path) -> dict[tuple[int, int], float]:
    """Read elapsed seconds from a standard ``y_post_time.txt``.

    Args:
        path_time (Path): File generated by ``pei_vasp_univ_post``.

    Returns:
        dict[tuple[int, int], float]: ``(KPAR, NCORE) -> elapsed seconds``.
    """
    if not path_time.is_file():
        fail("post-time file not found: %s" % path_time)

    dict_seconds = {}
    lunknown = []
    for line in path_time.read_text(encoding="utf-8").splitlines():
        match_time = TIME_PATTERN.search(line)
        if match_time is None:
            continue
        label = match_time.group(1)
        match_case = CASE_PATTERN.fullmatch(label)
        if match_case is None:
            lunknown.append(label)
            continue
        pair = (int(match_case.group(1)), int(match_case.group(2)))
        if pair in dict_seconds:
            fail("duplicate timing row for KPAR=%d, NCORE=%d in %s"
                 % (pair[0], pair[1], path_time))
        dict_seconds[pair] = float(match_time.group(2))

    if lunknown:
        warn("ignored timing rows with unrecognized labels: %s"
             % ", ".join(sorted(set(lunknown))))
    if not dict_seconds:
        fail("no completed kpar_<KPAR>_ncore_<NCORE> timing rows found in %s"
             % path_time)
    return dict_seconds


def read_kpar_ncore_energies(path_data: Path) -> dict[tuple[int, int], float]:
    """Read ``energy(sigma->0)`` values from ``y_post_data.txt``.

    Args:
        path_data (Path): File generated by ``pei_vasp_univ_post``.

    Returns:
        dict[tuple[int, int], float]: ``(KPAR, NCORE) -> total energy`` in eV.
    """
    if not path_data.is_file():
        fail("post-data file not found: %s" % path_data)

    dict_energy = {}
    lunknown = []
    for line in path_data.read_text(encoding="utf-8").splitlines():
        match_energy = ENERGY_PATTERN.search(line)
        if match_energy is None:
            continue
        label = match_energy.group(1)
        match_case = CASE_PATTERN.fullmatch(label)
        if match_case is None:
            lunknown.append(label)
            continue
        pair = (int(match_case.group(1)), int(match_case.group(2)))
        if pair in dict_energy:
            fail("duplicate energy row for KPAR=%d, NCORE=%d in %s"
                 % (pair[0], pair[1], path_data))
        dict_energy[pair] = float(match_energy.group(2))

    if lunknown:
        warn("ignored energy rows with unrecognized labels: %s"
             % ", ".join(sorted(set(lunknown))))
    if not dict_energy:
        fail("no kpar_<KPAR>_ncore_<NCORE> energy rows found in %s"
             % path_data)
    return dict_energy


def read_vasp_natoms(path_structure: Path) -> int:
    """Read the atom count from a VASP 4/5 POSCAR-style file.

    Args:
        path_structure (Path): POSCAR or CONTCAR path.

    Returns:
        int: Total number of atoms.

    Raises:
        ValueError: If the atom-count line cannot be parsed.
    """
    lline = path_structure.read_text(encoding="utf-8").splitlines()
    if len(lline) < 7:
        raise ValueError("fewer than seven lines")

    # VASP 4 places counts on line 6; VASP 5 inserts element names there and
    # moves counts to line 7. Only the count is needed, so no POTCAR lookup is
    # required for old structures whose comment does not contain element names.
    for index in (5, 6):
        ltoken = lline[index].split("!", maxsplit=1)[0].split()
        try:
            lcount = [int(token) for token in ltoken]
        except ValueError:
            continue
        if lcount and sum(lcount) > 0 and all(count >= 0 for count in lcount):
            return sum(lcount)
    raise ValueError("no positive atom-count line at POSCAR line 6 or 7")


def get_kpar_ncore_natoms(path_workflow: Path) -> int:
    """Find one reference structure and return its atom count.

    The relaxed source is preferred because it is the workflow's physical
    reference. A generated case is an equivalent fallback: every case copied
    that same structure to ``POSCAR``.

    Args:
        path_workflow (Path): KPAR/NCORE workflow directory.

    Returns:
        int: Number of atoms in each benchmark calculation.
    """
    path_relax = path_workflow.parent / "y_full_relax"
    lcandidate = [path_relax / "CONTCAR", path_relax / "POSCAR"]
    for path_case in sorted((path_workflow / "y_dir").iterdir()):
        if path_case.is_dir():
            lcandidate.extend([path_case / "POSCAR", path_case / "CONTCAR"])

    linvalid = []
    for path_structure in lcandidate:
        if not path_structure.is_file():
            continue
        try:
            natoms = read_vasp_natoms(path_structure)
        except (OSError, UnicodeError, ValueError) as exc:
            linvalid.append("%s (%s)" % (path_structure, exc))
            continue
        print("🧮 atoms        : %d from %s" % (natoms, path_structure))
        return natoms

    if linvalid:
        warn("unreadable reference structures: %s" % "; ".join(linvalid))
    fail("no usable CONTCAR/POSCAR found in %s or its y_dir cases"
         % path_relax)


def get_delta_energies(
        dict_energy: dict[tuple[int, int], float],
        natoms: int) -> dict[tuple[int, int], float]:
    """Convert total energies to ``(E - E0)`` in meV/atom.

    Args:
        dict_energy (dict[tuple[int, int], float]): Total energies in eV.
        natoms (int): Number of atoms in each benchmark case.

    Returns:
        dict[tuple[int, int], float]: Relative energies in meV/atom, using the
        minimum measured total energy as ``E0``.
    """
    if not dict_energy:
        fail("at least one completed energy is required")
    if natoms <= 0:
        fail("natoms must be positive")
    energy0 = min(dict_energy.values())
    return {
        pair: (energy - energy0) * 1000.0 / natoms
        for pair, energy in dict_energy.items()
    }


def get_missing_pairs(dict_seconds: dict[tuple[int, int], float]) -> list[tuple[int, int]]:
    """Return default benchmark pairs that have no elapsed time yet."""
    lmissing = []
    for kpar in KPAR_ORDER:
        for ncore in EXPECTED_PAIRS[kpar]:
            if (kpar, ncore) not in dict_seconds:
                lmissing.append((kpar, ncore))
    return lmissing


def write_kpar_ncore_times(
        dict_seconds: dict[tuple[int, int], float],
        dict_energy: dict[tuple[int, int], float],
        dict_delta_energy: dict[tuple[int, int], float],
        natoms: int,
        path_save: Path) -> None:
    """Write timing/energy data and the measured fastest combination.

    Args:
        dict_seconds (dict[tuple[int, int], float]): Parsed elapsed seconds.
        dict_energy (dict[tuple[int, int], float]): Completed total energies in eV.
        dict_delta_energy (dict[tuple[int, int], float]): Relative energies in
            meV/atom.
        natoms (int): Number of atoms in each benchmark case.
        path_save (Path): Output text path.
    """
    best_pair = min(dict_seconds, key=dict_seconds.get)
    energy0 = min(dict_energy.values())
    lline = [
        "# KPAR/NCORE VASP timing/energy benchmark",
        "# best: KPAR=%d NCORE=%d time_min=%.6f"
        % (best_pair[0], best_pair[1], dict_seconds[best_pair] / 60.0),
        "# natoms=%d E0_eV=%.10f" % (natoms, energy0),
        "# KPAR NCORE elapsed_seconds time_min energy_eV delta_energy_meV_per_atom",
    ]
    for kpar in KPAR_ORDER:
        lpairs = sorted(
            [pair for pair in dict_seconds if pair[0] == kpar],
            key=lambda pair: pair[1],
        )
        for pair in lpairs:
            seconds = dict_seconds[pair]
            energy = dict_energy.get(pair, float("nan"))
            delta_energy = dict_delta_energy.get(pair, float("nan"))
            lline.append("%6d %6d %15.6f %12.6f %18.10f %25.10f"
                         % (pair[0], pair[1], seconds, seconds / 60.0,
                            energy, delta_energy))
    path_save.write_text("\n".join(lline) + "\n", encoding="utf-8")


def post_kpar_ncore(path_workflow: str = None, run_post: bool = True,
                     save_fig_path: str = None,
                     save_txt_path: str = None) -> dict[tuple[int, int], float]:
    """Run standard post-processing and create timing/energy outputs.

    Args:
        path_workflow (str): Directory containing ``y_dir``.
        run_post (bool): Run ``pei_vasp_univ_post`` before reading times.
        save_fig_path (str): Figure path. Defaults to
            ``p_post_kpar_ncore.pdf`` inside the workflow.
        save_txt_path (str): Table path. Defaults to
            ``p_post_kpar_ncore.txt`` inside the workflow.

    Returns:
        dict[tuple[int, int], float]: Parsed elapsed seconds.
    """
    ### check ------------------------------------------------------------------
    if path_workflow is None:
        fail("path_workflow is required")
    path_workflow = Path(path_workflow).resolve()
    if not path_workflow.is_dir():
        fail("workflow directory not found: %s" % path_workflow)
    if not (path_workflow / "y_dir").is_dir():
        fail("y_dir not found under %s" % path_workflow)
    # to here: the standard workflow layout is available

    ### prepare ----------------------------------------------------------------
    if run_post:
        run_univ_post(path_workflow)
    path_time = path_workflow / "y_post_time.txt"
    path_data = path_workflow / "y_post_data.txt"
    dict_seconds = read_kpar_ncore_times(path_time)
    dict_energy_all = read_kpar_ncore_energies(path_data)
    lmissing_energy = sorted(set(dict_seconds) - set(dict_energy_all))
    lextra_energy = sorted(set(dict_energy_all) - set(dict_seconds))
    if lmissing_energy:
        warn("completed timing rows without energy: %s"
             % ", ".join("(%d,%d)" % pair for pair in lmissing_energy))
    if lextra_energy:
        warn("ignored energies without completed timing rows: %s"
             % ", ".join("(%d,%d)" % pair for pair in lextra_energy))
    dict_energy = {
        pair: dict_energy_all[pair]
        for pair in dict_seconds if pair in dict_energy_all
    }
    if not dict_energy:
        fail("no completed benchmark has both elapsed time and energy")
    natoms = get_kpar_ncore_natoms(path_workflow)
    dict_delta_energy = get_delta_energies(dict_energy, natoms)
    path_fig = (Path(save_fig_path).resolve() if save_fig_path
                else path_workflow / "p_post_kpar_ncore.pdf")
    path_txt = (Path(save_txt_path).resolve() if save_txt_path
                else path_workflow / "p_post_kpar_ncore.txt")
    # to here: matched timing/energy data and output paths are ready

    ### main -------------------------------------------------------------------
    write_kpar_ncore_times(
        dict_seconds, dict_energy, dict_delta_energy, natoms, path_txt)
    dict_minutes = {
        pair: seconds / 60.0 for pair, seconds in dict_seconds.items()
    }
    lxtick = sorted({
        ncore for lncore in EXPECTED_PAIRS.values() for ncore in lncore
    })
    my_plot_kpar_ncore(
        dict_time=dict_minutes,
        dict_delta_energy=dict_delta_energy,
        lkpar=KPAR_ORDER,
        lncore=lxtick,
        if_save=True,
        savefile=path_fig,
        if_close=True,
    )
    lmissing = get_missing_pairs(dict_seconds)
    best_pair = min(dict_seconds, key=dict_seconds.get)
    print("\n================ 📊 Summary")
    print("completed=%d    missing=%d" % (len(dict_seconds), len(lmissing)))
    if lmissing:
        warn("missing elapsed times: %s"
             % ", ".join("(%d,%d)" % pair for pair in lmissing))
    print("✅ best measured: KPAR=%d NCORE=%d time=%.6f min"
          % (best_pair[0], best_pair[1], dict_seconds[best_pair] / 60.0))
    print("✅ energy E0   : %.10f eV; max ΔE=%.6f meV/atom"
          % (min(dict_energy.values()), max(dict_delta_energy.values())))
    print("📄 table : %s" % path_txt)
    print("📈 figure: %s" % path_fig)
    print("🎉 Done: KPAR/NCORE timing/energy post-processing complete")
    return dict_seconds
